// TODO

use specta::{Type, TypeCollection};
use specta_typescript::{Any, Typescript, Unknown};

#[derive(Type)]
struct Demo {
    a: Any<()>,
    b: Unknown<()>,
}

#[test]
fn typescript() {
    let types = TypeCollection::default().register::<Demo>();

    // TODO: Snapshot testing
    assert_eq!(
        Typescript::default().export(&types),
        Ok("// This file has been generated by Specta. DO NOT EDIT.\n\nexport type Demo = { a: any; b: unknown }\n\n".into())
    );
}

// TODO: Unit test `export_to`'s fs operations
