#![allow(clippy::unwrap_used, dead_code, missing_docs)]

use specta::{Type, Types};
use specta_swift::{GenericStyle, IndentStyle, NamingConvention, OptionalStyle, Swift};

/// Comprehensive example showcasing ALL configuration options for specta-swift
///
/// This example demonstrates every configuration option available in the Swift exporter,
/// showing how different settings affect the generated Swift code.
///
/// Sample types for demonstration
#[derive(Type)]
struct User {
    user_id: u32,
    full_name: String,
    email_address: Option<String>,
    is_verified: bool,
}

#[derive(Type)]
enum ApiResponse<T> {
    Success { data: T, status_code: u16 },
    Error { message: String, error_code: u32 },
    Loading { progress: f32 },
}

#[derive(Type)]
struct GenericContainer<T, U> {
    primary: T,
    secondary: U,
    metadata: Option<Vec<(String, String)>>,
}

fn main() {
    println!("🚀 Configuration Options Example - All Swift exporter settings");
    println!("{}", "=".repeat(70));

    // Sample types for all examples
    let types = Types::default()
        .register::<User>()
        .register::<ApiResponse<String>>()
        .register::<GenericContainer<String, u32>>();

    // 1. DEFAULT CONFIGURATION
    println!("\n📋 1. DEFAULT CONFIGURATION");
    println!("{}", "-".repeat(40));
    let default_swift = Swift::default();
    let default_output = default_swift.export(&types, specta_serde::Format).unwrap();
    println!("{}", default_output);
    default_swift
        .export_to(
            "./examples/generated/DefaultConfig.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Default configuration exported to DefaultConfig.swift");

    // 2. CUSTOM HEADER
    println!("\n📋 2. CUSTOM HEADER");
    println!("{}", "-".repeat(40));
    let custom_header = Swift::new()
        .header("// Generated by MyAwesomeApp v2.0\n// Custom header with app info\n// DO NOT EDIT MANUALLY");
    let header_output = custom_header.export(&types, specta_serde::Format).unwrap();
    println!("{}", header_output);
    custom_header
        .export_to(
            "./examples/generated/CustomHeader.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Custom header exported to CustomHeader.swift");

    // 3. DIFFERENT NAMING CONVENTIONS
    println!("\n📋 3. NAMING CONVENTIONS");
    println!("{}", "-".repeat(40));

    // PascalCase (default)
    let pascal_case = Swift::new().naming(NamingConvention::PascalCase);
    let pascal_output = pascal_case.export(&types, specta_serde::Format).unwrap();
    println!("PascalCase output:\n{}", pascal_output);
    pascal_case
        .export_to(
            "./examples/generated/PascalCase.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // camelCase
    let camel_case = Swift::new().naming(NamingConvention::CamelCase);
    let camel_output = camel_case.export(&types, specta_serde::Format).unwrap();
    println!("camelCase output:\n{}", camel_output);
    camel_case
        .export_to(
            "./examples/generated/CamelCase.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // snake_case
    let snake_case = Swift::new().naming(NamingConvention::SnakeCase);
    let snake_output = snake_case.export(&types, specta_serde::Format).unwrap();
    println!("snake_case output:\n{}", snake_output);
    snake_case
        .export_to(
            "./examples/generated/SnakeCase.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Naming conventions exported to separate files");

    // 4. INDENTATION STYLES
    println!("\n📋 4. INDENTATION STYLES");
    println!("{}", "-".repeat(40));

    // Spaces (default: 4 spaces)
    let spaces_4 = Swift::new().indent(IndentStyle::Spaces(4));
    let spaces_output = spaces_4.export(&types, specta_serde::Format).unwrap();
    println!("4 Spaces indentation:\n{}", spaces_output);
    spaces_4
        .export_to(
            "./examples/generated/Spaces4.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // 2 Spaces
    let spaces_2 = Swift::new().indent(IndentStyle::Spaces(2));
    let spaces2_output = spaces_2.export(&types, specta_serde::Format).unwrap();
    println!("2 Spaces indentation:\n{}", spaces2_output);
    spaces_2
        .export_to(
            "./examples/generated/Spaces2.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // Tabs
    let tabs = Swift::new().indent(IndentStyle::Tabs);
    let tabs_output = tabs.export(&types, specta_serde::Format).unwrap();
    println!("Tabs indentation:\n{}", tabs_output);
    tabs.export_to(
        "./examples/generated/Tabs.swift",
        &types,
        specta_serde::Format,
    )
    .unwrap();
    println!("✅ Indentation styles exported to separate files");

    // 5. GENERIC STYLES
    println!("\n📋 5. GENERIC STYLES");
    println!("{}", "-".repeat(40));

    // Protocol constraints (default)
    let protocol_generics = Swift::new().generics(GenericStyle::Protocol);
    let protocol_output = protocol_generics
        .export(&types, specta_serde::Format)
        .unwrap();
    println!("Protocol constraints:\n{}", protocol_output);
    protocol_generics
        .export_to(
            "./examples/generated/ProtocolGenerics.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // Typealias constraints
    let typealias_generics = Swift::new().generics(GenericStyle::Typealias);
    let typealias_output = typealias_generics
        .export(&types, specta_serde::Format)
        .unwrap();
    println!("Typealias constraints:\n{}", typealias_output);
    typealias_generics
        .export_to(
            "./examples/generated/TypealiasGenerics.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Generic styles exported to separate files");

    // 6. OPTIONAL STYLES
    println!("\n📋 6. OPTIONAL STYLES");
    println!("{}", "-".repeat(40));

    // Question mark syntax (default)
    let question_mark = Swift::new().optionals(OptionalStyle::QuestionMark);
    let question_output = question_mark.export(&types, specta_serde::Format).unwrap();
    println!("Question mark syntax:\n{}", question_output);
    question_mark
        .export_to(
            "./examples/generated/QuestionMark.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();

    // Optional type syntax
    let optional_type = Swift::new().optionals(OptionalStyle::Optional);
    let optional_output = optional_type.export(&types, specta_serde::Format).unwrap();
    println!("Optional type syntax:\n{}", optional_output);
    optional_type
        .export_to(
            "./examples/generated/OptionalType.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Optional styles exported to separate files");

    // 7. ADDITIONAL PROTOCOLS
    println!("\n📋 7. ADDITIONAL PROTOCOLS");
    println!("{}", "-".repeat(40));
    let with_protocols = Swift::new()
        .add_protocol("Equatable")
        .add_protocol("Hashable")
        .add_protocol("CustomStringConvertible");
    let protocols_output = with_protocols.export(&types, specta_serde::Format).unwrap();
    println!("With additional protocols:\n{}", protocols_output);
    with_protocols
        .export_to(
            "./examples/generated/WithProtocols.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Additional protocols exported to WithProtocols.swift");

    // 8. FORMAT PARAMETER SERDE TRANSFORMS
    println!("\n📋 8. FORMAT PARAMETER SERDE TRANSFORMS");
    println!("{}", "-".repeat(40));
    let with_serde = Swift::new();
    let serde_output = with_serde.export(&types, specta_serde::Format).unwrap();
    println!("With Serde format transform:\n{}", serde_output);
    with_serde
        .export_to(
            "./examples/generated/WithSerde.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Serde format transform example exported to WithSerde.swift");

    // 9. COMBINED CUSTOM CONFIGURATION
    println!("\n📋 9. COMBINED CUSTOM CONFIGURATION");
    println!("{}", "-".repeat(40));
    let combined = Swift::new()
        .header("// My Custom App Types\n// Generated with love ❤️")
        .naming(NamingConvention::CamelCase)
        .indent(IndentStyle::Spaces(2))
        .generics(GenericStyle::Typealias)
        .optionals(OptionalStyle::Optional)
        .add_protocol("Equatable")
        .add_protocol("Hashable");

    let combined_output = combined.export(&types, specta_serde::Format).unwrap();
    println!("Combined custom configuration:\n{}", combined_output);
    combined
        .export_to(
            "./examples/generated/CombinedConfig.swift",
            &types,
            specta_serde::Format,
        )
        .unwrap();
    println!("✅ Combined configuration exported to CombinedConfig.swift");

    println!("\n🎉 All configuration examples completed!");
    println!("\n📁 Generated files:");
    println!("• DefaultConfig.swift - Default settings");
    println!("• CustomHeader.swift - Custom header");
    println!("• PascalCase.swift, CamelCase.swift, SnakeCase.swift - Naming conventions");
    println!("• Spaces4.swift, Spaces2.swift, Tabs.swift - Indentation styles");
    println!("• ProtocolGenerics.swift, TypealiasGenerics.swift - Generic styles");
    println!("• QuestionMark.swift, OptionalType.swift - Optional styles");
    println!("• WithProtocols.swift - Additional protocols");
    println!("• WithSerde.swift - Serde validation");
    println!("• CombinedConfig.swift - Combined custom settings");
}
