#![allow(clippy::unwrap_used, dead_code, missing_docs)]

use std::fs;

use serde::{Deserialize, Serialize};
use specta::{Type, Types};
use specta_jsonschema::{JsonSchema, SchemaVersion};

#[derive(Type)]
struct Primitives {
    bool_field: bool,
    string_field: String,
    char_field: char,
    i8_field: i8,
    u16_field: u16,
    i32_field: i32,
    u64_field: u64,
    f32_field: f32,
    f64_field: f64,
}

#[derive(Type)]
struct User {
    id: u32,
    name: String,
    email: Option<String>,
}

#[derive(Type)]
struct Collections {
    tags: Vec<String>,
    tuple: (String, u32),
    map: std::collections::HashMap<String, u32>,
}

#[derive(Type)]
enum Status {
    Active,
    Inactive,
    Pending,
}

#[derive(Type)]
enum Message {
    Quit,
    Move { x: i32, y: i32 },
    Write(String),
}

#[derive(Type)]
struct Wrapper<T> {
    value: T,
}

#[derive(Type)]
struct UsesGenerics {
    user: Wrapper<User>,
    count: Wrapper<u32>,
}

#[derive(Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
struct SerdeUser {
    user_id: u32,
    full_name: String,
}

#[derive(Serialize, Deserialize, Type)]
#[serde(tag = "type", content = "data")]
enum SerdeMessage {
    Text { body: String },
    Count(u32),
}

#[test]
fn exports_metadata_and_primitives() {
    let types = Types::default().register::<Primitives>();
    let schema = JsonSchema::default()
        .title("Example")
        .description("Example schemas")
        .comment("Generated by Specta")
        .export_value(&types, specta_serde::Format)
        .unwrap();

    insta::assert_json_snapshot!(schema);
}

#[test]
fn exports_structs_collections_and_enums() {
    let types = Types::default()
        .register::<User>()
        .register::<Collections>()
        .register::<Status>()
        .register::<Message>();
    let schema = JsonSchema::default()
        .export_value(&types, specta_serde::Format)
        .unwrap();

    insta::assert_json_snapshot!(schema);
}

#[test]
fn exports_draft7_tuple_syntax() {
    let types = Types::default().register::<Collections>();
    let schema = JsonSchema::default()
        .schema_version(SchemaVersion::Draft7)
        .export_value(&types, specta_serde::Format)
        .unwrap();

    insta::assert_json_snapshot!(schema);
}

#[test]
fn exports_generic_instantiations() {
    let types = Types::default().register::<UsesGenerics>();
    let schema = JsonSchema::default()
        .export_value(&types, specta_serde::Format)
        .unwrap();

    insta::assert_json_snapshot!(schema);
}

#[test]
fn applies_serde_format() {
    let types = Types::default()
        .register::<SerdeUser>()
        .register::<SerdeMessage>();
    let schema = JsonSchema::default()
        .export_value(&types, specta_serde::Format)
        .unwrap();

    insta::assert_json_snapshot!(schema);
}

#[test]
fn export_to_writes_single_file() {
    let types = Types::default().register::<User>();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("target")
        .join(format!("jsonschema-test-{}.json", std::process::id()));

    JsonSchema::default()
        .export_to(&path, &types, specta_serde::Format)
        .unwrap();

    let schema = fs::read_to_string(&path).unwrap();
    fs::remove_file(&path).unwrap();
    assert!(schema.contains("\"$schema\""));
    assert!(schema.contains("\"User\""));
}
