use std::{borrow::Cow, fmt, path::Path};

use specta::{Format, Types, datatype::DataType};

use crate::{Error, render};

/// Controls the shape of generated Java source files.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Layout {
    /// Nest all generated declarations in one configurable wrapper class.
    #[default]
    FlatFile,
    /// Flatten types into one wrapper and prefix each name with its Rust module path.
    ModulePrefixedName,
    /// Generate one public source file for every named type.
    Files,
}

/// Controls how [`DataType::Nullable`] values are rendered.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum OptionalStyle {
    /// Use Java's ordinary nullable reference types without adding annotations.
    #[default]
    Nullable,
    /// Wrap nullable values in `java.util.Optional`.
    Optional,
}

impl fmt::Display for Layout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

/// Java 17 language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Java {
    /// Content written at the beginning of every generated file.
    pub header: Cow<'static, str>,
    /// Output layout.
    pub layout: Layout,
    pub(crate) package: Option<Cow<'static, str>>,
    pub(crate) class_name: Cow<'static, str>,
    pub(crate) raw: Vec<Cow<'static, str>>,
    pub(crate) optionals: OptionalStyle,
}

impl Default for Java {
    fn default() -> Self {
        Self {
            header: Cow::Borrowed(
                "// This file has been generated by Specta. Do not edit this file manually.",
            ),
            layout: Layout::FlatFile,
            package: None,
            class_name: Cow::Borrowed("Bindings"),
            raw: Vec::new(),
            optionals: OptionalStyle::Nullable,
        }
    }
}

impl Java {
    /// Construct an exporter using the default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Configure content written at the beginning of every generated file.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Configure the Java package for generated declarations.
    pub fn package(mut self, package: impl Into<Cow<'static, str>>) -> Self {
        self.package = Some(package.into());
        self
    }

    /// Configure the public wrapper class used by [`Layout::FlatFile`].
    pub fn class_name(mut self, name: impl Into<Cow<'static, str>>) -> Self {
        self.class_name = name.into();
        self
    }

    /// Configure the generated source layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Configure how nullable datatypes are represented.
    pub fn optionals(mut self, style: OptionalStyle) -> Self {
        self.optionals = style;
        self
    }

    /// Append raw Java source to the generated wrapper or the files-layout base-package helper.
    pub fn with_raw(mut self, raw: impl Into<Cow<'static, str>>) -> Self {
        self.raw.push(raw.into());
        self
    }

    /// Export all types into a single Java source string.
    pub fn export(&self, types: &Types, format: impl Format) -> Result<String, Error> {
        if self.layout == Layout::Files {
            return Err(Error::export_requires_export_to(self.layout));
        }
        let types = format_types(types, &format)?;
        render::flat_file(self, &types)
    }

    /// Render one anonymous datatype with this exporter's Java configuration.
    pub fn inline(
        &self,
        types: &Types,
        datatype: &DataType,
        format: impl Format,
    ) -> Result<String, Error> {
        let formatted_types = format
            .map_types(types)
            .map_err(|source| Error::format("type graph formatter failed", source))?;
        let datatype = map_datatype(formatted_types.as_ref(), &format, datatype)?;
        render::inline(self, formatted_types.as_ref(), &datatype)
    }

    /// Export types to a file or directory, depending on [`Layout`].
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        types: &Types,
        format: impl Format,
    ) -> Result<(), Error> {
        let types = format_types(types, &format)?;
        match self.layout {
            Layout::FlatFile | Layout::ModulePrefixedName => {
                let path = path.as_ref();
                let expected = render::class_name(self)?;
                if path.file_name().and_then(|name| name.to_str())
                    != Some(format!("{expected}.java").as_str())
                {
                    return Err(Error::output_filename_mismatch(
                        expected,
                        path.to_path_buf(),
                    ));
                }
                if let Some(parent) = path.parent() {
                    std::fs::create_dir_all(parent)
                        .map_err(|source| Error::create_dir(parent.to_path_buf(), source))?;
                }
                let source = render::flat_file(self, &types)?;
                std::fs::write(path, source)
                    .map_err(|source| Error::write_file(path.to_path_buf(), source))
            }
            Layout::Files => render::files(self, path.as_ref(), &types),
        }
    }
}

fn format_types(types: &Types, format: &dyn Format) -> Result<Types, Error> {
    let types = format
        .map_types(types)
        .map_err(|source| Error::format("type graph formatter failed", source))?;
    map_datatypes(types, format)
}

fn map_datatypes(types: Cow<'_, Types>, format: &dyn Format) -> Result<Types, Error> {
    let original = types.as_ref();
    let mut mapped = original.clone();
    let mut error = None;
    mapped.iter_mut(|ndt| {
        if error.is_some() {
            return;
        }
        let Some(ty) = &ndt.ty else { return };
        match map_datatype(original, format, ty) {
            Ok(ty) => ndt.ty = Some(ty),
            Err(err) => {
                error = Some(err.with_path(ndt.name.to_string()).with_named_datatype(ndt));
            }
        }
    });
    error.map_or_else(|| Ok(mapped), Err)
}

fn map_datatype(
    types: &Types,
    format: &dyn Format,
    dt: &specta::datatype::DataType,
) -> Result<specta::datatype::DataType, Error> {
    use specta::datatype::{DataType, Fields, NamedReferenceType, Reference};

    let mut dt = format
        .map_type(types, dt)
        .map_err(|source| Error::format("datatype formatter failed", source))?
        .into_owned();
    let map_fields = |fields: &mut Fields| -> Result<(), Error> {
        match fields {
            Fields::Unit => Ok(()),
            Fields::Unnamed(fields) => fields.fields.iter_mut().try_for_each(|field| {
                if let Some(ty) = &mut field.ty {
                    *ty = map_datatype(types, format, ty)?;
                }
                Ok(())
            }),
            Fields::Named(fields) => fields.fields.iter_mut().try_for_each(|(_, field)| {
                if let Some(ty) = &mut field.ty {
                    *ty = map_datatype(types, format, ty)?;
                }
                Ok(())
            }),
        }
    };
    match &mut dt {
        DataType::Primitive(_)
        | DataType::Generic(_)
        | DataType::Reference(Reference::Opaque(_)) => {}
        DataType::List(list) => *list.ty = map_datatype(types, format, &list.ty)?,
        DataType::Map(map) => {
            let key = map_datatype(types, format, map.key_ty())?;
            let value = map_datatype(types, format, map.value_ty())?;
            map.set_key_ty(key);
            map.set_value_ty(value);
        }
        DataType::Struct(value) => map_fields(&mut value.fields)?,
        DataType::Enum(value) => {
            for (_, variant) in &mut value.variants {
                map_fields(&mut variant.fields)?;
            }
        }
        DataType::Tuple(value) => {
            for element in &mut value.elements {
                *element = map_datatype(types, format, element)?;
            }
        }
        DataType::Nullable(value) => **value = map_datatype(types, format, value)?,
        DataType::Intersection(values) => {
            for value in values {
                *value = map_datatype(types, format, value)?;
            }
        }
        DataType::Reference(Reference::Named(reference)) => match &mut reference.inner {
            NamedReferenceType::Reference { generics, .. } => {
                for (_, generic) in generics {
                    *generic = map_datatype(types, format, generic)?;
                }
            }
            NamedReferenceType::Inline { dt, .. } => {
                **dt = map_datatype(types, format, dt)?;
            }
            NamedReferenceType::Recursive(_) => {}
        },
    }
    Ok(dt)
}
