use std::{borrow::Cow, collections::BTreeMap, fmt, path::Path};

use specta::{
    Format, Types,
    datatype::{DataType, Fields, NamedReferenceType, Reference},
};

use crate::{Error, primitives};

/// Controls how generated Go declarations are split across files.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Layout {
    /// Place every declaration in one Go file.
    #[default]
    FlatFile,
    /// Place each named datatype in its own Go file in one package.
    Files,
}

impl fmt::Display for Layout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

/// Go language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Go {
    /// Custom text placed before the generated-file notice.
    pub header: Cow<'static, str>,
    /// Output layout.
    pub layout: Layout,
    pub(crate) package_name: Cow<'static, str>,
    pub(crate) prelude: Cow<'static, str>,
    pub(crate) raw: Vec<Cow<'static, str>>,
}

impl Default for Go {
    fn default() -> Self {
        Self {
            header: Cow::Borrowed(""),
            layout: Layout::FlatFile,
            package_name: Cow::Borrowed("bindings"),
            prelude: Cow::Borrowed("// Code generated by Specta. DO NOT EDIT."),
            raw: Vec::new(),
        }
    }
}

impl Go {
    /// Creates a Go exporter with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the package declaration used by every generated file.
    pub fn package_name(mut self, name: impl Into<Cow<'static, str>>) -> Self {
        self.package_name = name.into();
        self
    }

    /// Sets custom text placed before the generated-file notice.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Sets the output layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Sets the generated-file notice placed before the package declaration.
    pub fn framework_prelude(mut self, prelude: impl Into<Cow<'static, str>>) -> Self {
        self.prelude = prelude.into();
        self
    }

    /// Appends raw Go declarations after generated types.
    pub fn with_raw(mut self, raw: impl Into<Cow<'static, str>>) -> Self {
        self.raw.push(raw.into());
        self
    }

    /// Exports all types to one Go source string.
    ///
    /// [`Layout::Files`] requires [`Self::export_to`].
    pub fn export(&self, types: &Types, format: impl Format) -> Result<String, Error> {
        if self.layout == Layout::Files {
            return Err(Error::ExportRequiresExportTo(self.layout));
        }

        validate_package_name(&self.package_name)?;
        let types = format_types(types, &format)?;
        let body = primitives::export(self, types.as_ref(), types.as_ref().into_sorted_iter())?;
        Ok(self.render_file(&body, true))
    }

    /// Exports types to a file or directory.
    ///
    /// Flat-file layout expects a file path. Files layout expects a directory and
    /// creates one `.go` file per named datatype plus `specta.go` for raw code.
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        types: &Types,
        format: impl Format,
    ) -> Result<(), Error> {
        validate_package_name(&self.package_name)?;
        let path = path.as_ref();
        let types = format_types(types, &format)?;
        let types = types.as_ref();

        match self.layout {
            Layout::FlatFile => write_file(
                path,
                &self.render_file(
                    &primitives::export(self, types, types.into_sorted_iter())?,
                    true,
                ),
            ),
            Layout::Files => {
                if path.exists() && !path.is_dir() {
                    return Err(Error::Metadata {
                        path: path.to_path_buf(),
                        source: std::io::Error::new(
                            std::io::ErrorKind::NotADirectory,
                            "files layout requires a directory",
                        ),
                    });
                }
                std::fs::create_dir_all(path).map_err(|source| Error::CreateDir {
                    path: path.to_path_buf(),
                    source,
                })?;

                // Validate package-wide symbol uniqueness before splitting the declarations.
                let _ = primitives::export(self, types, types.into_sorted_iter())?;

                let mut files = BTreeMap::new();
                for ndt in types.into_sorted_iter().filter(|ndt| ndt.ty.is_some()) {
                    let file_name = primitives::file_name(ndt)?;
                    let body = primitives::export(self, types, std::iter::once(ndt))?;
                    if files.insert(file_name.clone(), body).is_some() {
                        return Err(Error::DuplicateName {
                            path: "output files".into(),
                            name: file_name,
                        });
                    }
                }

                if !self.raw.iter().all(|raw| raw.is_empty()) || files.is_empty() {
                    files.entry("specta.go".into()).or_default();
                }

                for (name, body) in files {
                    let include_raw = name == "specta.go";
                    write_file(&path.join(name), &self.render_file(&body, include_raw))?;
                }
                Ok(())
            }
        }
    }

    fn render_file(&self, body: &str, include_raw: bool) -> String {
        let mut out = String::new();
        if !self.header.is_empty() {
            out.push_str(self.header.trim_end());
            out.push_str("\n\n");
        }
        if !self.prelude.is_empty() {
            out.push_str(self.prelude.trim_end());
            out.push('\n');
        }
        out.push_str("\npackage ");
        out.push_str(&self.package_name);
        out.push_str("\n\n");
        out.push_str(body);
        for raw in self.raw.iter().filter(|raw| include_raw && !raw.is_empty()) {
            if !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(raw.trim());
            out.push('\n');
        }
        out
    }
}

impl AsRef<Go> for Go {
    fn as_ref(&self) -> &Go {
        self
    }
}

impl AsMut<Go> for Go {
    fn as_mut(&mut self) -> &mut Go {
        self
    }
}

fn format_types<'a>(types: &'a Types, format: &dyn Format) -> Result<Cow<'a, Types>, Error> {
    let mapped = match format
        .map_types(types)
        .map_err(|source| Error::format("type graph", source))?
    {
        Cow::Borrowed(_) => Cow::Borrowed(types),
        Cow::Owned(types) => Cow::Owned(types),
    };
    let graph = mapped.as_ref();
    let mut output = graph.clone();
    let mut error = None;
    output.iter_mut(|ndt| {
        if error.is_some() {
            return;
        }
        let Some(ty) = ndt.ty.as_ref() else {
            return;
        };
        match map_datatype_format(format, graph, ty, &rust_type_path(ndt)) {
            Ok(ty) => ndt.ty = Some(ty),
            Err(err) => error = Some(err),
        }
    });
    error.map_or_else(|| Ok(Cow::Owned(output)), Err)
}

fn map_datatype_format(
    format: &dyn Format,
    types: &Types,
    dt: &DataType,
    path: &str,
) -> Result<DataType, Error> {
    if matches!(dt, DataType::Generic(_)) {
        return Ok(dt.clone());
    }

    let mapped = match format.map_type(types, dt) {
        Ok(Cow::Borrowed(dt)) => dt.clone(),
        Ok(Cow::Owned(dt)) => dt,
        Err(source)
            if contains_generic_reference(dt)
                && source.to_string().contains("Unresolved generic reference") =>
        {
            dt.clone()
        }
        Err(source) => return Err(Error::format(path, source)),
    };
    map_datatype_children(format, types, mapped, path)
}

fn map_datatype_children(
    format: &dyn Format,
    types: &Types,
    mut dt: DataType,
    path: &str,
) -> Result<DataType, Error> {
    match &mut dt {
        DataType::Primitive(_)
        | DataType::Generic(_)
        | DataType::Reference(Reference::Opaque(_)) => {}
        DataType::List(list) => {
            *list.ty =
                map_datatype_format(format, types, &list.ty, &format!("{path}.<list_item>"))?;
        }
        DataType::Map(map) => {
            let key =
                map_datatype_format(format, types, map.key_ty(), &format!("{path}.<map_key>"))?;
            let value = map_datatype_format(
                format,
                types,
                map.value_ty(),
                &format!("{path}.<map_value>"),
            )?;
            map.set_key_ty(key);
            map.set_value_ty(value);
        }
        DataType::Nullable(inner) => {
            **inner = map_datatype_format(format, types, inner, path)?;
        }
        DataType::Struct(strct) => {
            map_fields_format(format, types, &mut strct.fields, path)?;
        }
        DataType::Enum(enm) => {
            for (variant, metadata) in &mut enm.variants {
                map_fields_format(
                    format,
                    types,
                    &mut metadata.fields,
                    &format!("{path}.{variant}"),
                )?;
            }
        }
        DataType::Tuple(tuple) => {
            for (index, element) in tuple.elements.iter_mut().enumerate() {
                *element = map_datatype_format(format, types, element, &format!("{path}.{index}"))?;
            }
        }
        DataType::Intersection(elements) => {
            for element in elements {
                *element = map_datatype_format(format, types, element, path)?;
            }
        }
        DataType::Reference(Reference::Named(reference)) => match &mut reference.inner {
            NamedReferenceType::Inline { dt, .. } => {
                **dt = map_datatype_format(format, types, dt, path)?;
            }
            NamedReferenceType::Reference { generics, .. } => {
                for (_, generic) in generics {
                    *generic = map_datatype_format(format, types, generic, path)?;
                }
            }
            NamedReferenceType::Recursive(_) => {}
        },
    }
    Ok(dt)
}

fn map_fields_format(
    format: &dyn Format,
    types: &Types,
    fields: &mut Fields,
    path: &str,
) -> Result<(), Error> {
    match fields {
        Fields::Unit => {}
        Fields::Unnamed(fields) => {
            for (index, field) in fields.fields.iter_mut().enumerate() {
                if let Some(ty) = field.ty.as_mut() {
                    *ty = map_datatype_format(format, types, ty, &format!("{path}.{index}"))?;
                }
            }
        }
        Fields::Named(fields) => {
            for (name, field) in &mut fields.fields {
                if let Some(ty) = field.ty.as_mut() {
                    *ty = map_datatype_format(format, types, ty, &format!("{path}.{name}"))?;
                }
            }
        }
    }
    Ok(())
}

fn contains_generic_reference(dt: &DataType) -> bool {
    match dt {
        DataType::Primitive(_) | DataType::Reference(Reference::Opaque(_)) => false,
        DataType::Generic(_) => true,
        DataType::List(list) => contains_generic_reference(&list.ty),
        DataType::Map(map) => {
            contains_generic_reference(map.key_ty()) || contains_generic_reference(map.value_ty())
        }
        DataType::Nullable(inner) => contains_generic_reference(inner),
        DataType::Struct(strct) => fields_contain_generic(&strct.fields),
        DataType::Enum(enm) => enm
            .variants
            .iter()
            .any(|(_, variant)| fields_contain_generic(&variant.fields)),
        DataType::Tuple(tuple) => tuple.elements.iter().any(contains_generic_reference),
        DataType::Intersection(elements) => elements.iter().any(contains_generic_reference),
        DataType::Reference(Reference::Named(reference)) => match &reference.inner {
            NamedReferenceType::Inline { dt, .. } => contains_generic_reference(dt),
            NamedReferenceType::Reference { generics, .. } => generics
                .iter()
                .any(|(_, generic)| contains_generic_reference(generic)),
            NamedReferenceType::Recursive(_) => false,
        },
    }
}

fn fields_contain_generic(fields: &Fields) -> bool {
    match fields {
        Fields::Unit => false,
        Fields::Unnamed(fields) => fields
            .fields
            .iter()
            .filter_map(|field| field.ty.as_ref())
            .any(contains_generic_reference),
        Fields::Named(fields) => fields
            .fields
            .iter()
            .filter_map(|(_, field)| field.ty.as_ref())
            .any(contains_generic_reference),
    }
}

fn rust_type_path(ndt: &specta::datatype::NamedDataType) -> String {
    if ndt.module_path.is_empty() {
        ndt.name.to_string()
    } else {
        format!("{}::{}", ndt.module_path, ndt.name)
    }
}

fn validate_package_name(name: &str) -> Result<(), Error> {
    let mut chars = name.chars();
    let valid = chars
        .next()
        .is_some_and(|ch| ch == '_' || ch.is_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_alphanumeric())
        && !crate::reserved_names::GO_KEYWORDS.contains(&name);
    valid
        .then_some(())
        .ok_or_else(|| Error::InvalidPackageName(name.to_string()))
}

fn write_file(path: &Path, content: &str) -> Result<(), Error> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        std::fs::create_dir_all(parent).map_err(|source| Error::CreateDir {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    std::fs::write(path, content).map_err(|source| Error::WriteFile {
        path: path.to_path_buf(),
        source,
    })
}
