use std::{
    borrow::Cow,
    cell::RefCell,
    collections::{BTreeMap, BTreeSet, HashMap, HashSet},
    fmt,
    ops::Deref,
    path::{Path, PathBuf},
    sync::Arc,
};

use specta::{
    Format, Types,
    datatype::{DataType, Fields, NamedDataType, Reference},
};

use crate::{Error, primitives, references, reserved_names::RESERVED_TYPE_NAMES};

const GENERATED_FILE_MARKER: &str =
    "// This file has been generated by Specta's Valibot exporter. Do not edit this file manually.";

const RUNTIME_HELPERS: &str = r#"const $spectaIsRecord = (input: unknown): input is Record<string, unknown> => {
	if (typeof input !== "object" || input === null || Array.isArray(input)) return false;
	const prototype = Object.getPrototypeOf(input);
	return prototype === Object.prototype || prototype === null;
};
const $spectaEncodeKey = (key: string) => `$specta$${key}`;
const $spectaDecodeKey = (key: string) => key.slice("$specta$".length);
const $spectaEncodeObject = (input: Record<string, unknown>) =>
	Object.fromEntries(Object.entries(input).map(([key, value]) => [$spectaEncodeKey(key), value]));
const $spectaDecodeObject = (input: Record<string, unknown>) =>
	Object.fromEntries(Object.entries(input).map(([key, value]) => [$spectaDecodeKey(key), value]));
const $spectaDeepEncode = (input: unknown): unknown =>
	Array.isArray(input)
		? input.map($spectaDeepEncode)
		: $spectaIsRecord(input)
			? Object.fromEntries(
					Object.entries(input).map(([key, value]) => [
						$spectaEncodeKey(key),
						$spectaDeepEncode(value),
					]),
				)
			: input;
const $spectaDeepDecode = (input: unknown): unknown =>
	Array.isArray(input)
		? input.map($spectaDeepDecode)
		: $spectaIsRecord(input)
			? Object.fromEntries(
					Object.entries(input).map(([key, value]) => [
						$spectaDecodeKey(key),
						$spectaDeepDecode(value),
					]),
				)
			: input;
function $spectaObject<const TEntries extends v.ObjectEntries>(entries: TEntries, strict = false) {
	const encodedEntries = Object.fromEntries(
		Object.entries(entries).map(([key, schema]) => [$spectaEncodeKey(key), schema]),
	) as TEntries;
	const schema = strict ? v.strictObject(encodedEntries) : v.object(encodedEntries);
	return v.pipe(
		v.custom<Record<string, unknown>>($spectaIsRecord),
		v.transform($spectaEncodeObject),
		schema,
		v.transform($spectaDecodeObject),
	) as unknown as v.GenericSchema<
		v.InferInput<v.ObjectSchema<TEntries, undefined>>,
		v.InferOutput<v.ObjectSchema<TEntries, undefined>>
	>;
}
function $spectaRecord<
	const TKey extends v.GenericSchema<string, string>,
	const TValue extends v.GenericSchema,
>(
	key: TKey,
	value: TValue,
): v.GenericSchema<
	v.InferInput<v.RecordSchema<TKey, TValue, undefined>>,
	v.InferOutput<v.RecordSchema<TKey, TValue, undefined>>
> {
	const encodedKey = v.pipe(v.string(), v.transform($spectaDecodeKey), key, v.transform($spectaEncodeKey));
	return v.pipe(
		v.custom<Record<string, unknown>>($spectaIsRecord),
		v.transform($spectaEncodeObject),
		v.record(encodedKey, value),
		v.transform($spectaDecodeObject),
	) as unknown as v.GenericSchema<
		v.InferInput<v.RecordSchema<TKey, TValue, undefined>>,
		v.InferOutput<v.RecordSchema<TKey, TValue, undefined>>
	>;
}
function $spectaIntersect<const TOptions extends v.IntersectOptions>(options: TOptions) {
	const encodedOptions = options.map((option) =>
		v.pipe(option, v.transform($spectaDeepEncode)),
	) as v.IntersectOptions;
	return v.pipe(
		v.intersect(encodedOptions),
		v.transform($spectaDeepDecode),
	) as unknown as v.GenericSchema<
		v.InferInput<v.IntersectSchema<TOptions, undefined>>,
		v.InferOutput<v.IntersectSchema<TOptions, undefined>>
	>;
}"#;

/// TypeScript runtime support required by expressions from [`crate::primitives`].
///
/// Low-level callers should emit this fragment once after binding the Valibot namespace to `v`.
/// The high-level [`Valibot`] exporter includes it automatically.
pub fn runtime_helpers() -> &'static str {
    RUNTIME_HELPERS
}

/// Allows configuring the format of generated output.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Layout {
    /// Produce a TypeScript namespace for each Rust module.
    Namespaces,
    /// Flatten all types into one file with unmodified names.
    #[default]
    FlatFile,
    /// Flatten into one file with module prefixes added to each type name.
    ModulePrefixedName,
    /// Emit one file per Rust module path.
    Files,
}

impl fmt::Display for Layout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

#[derive(Clone)]
#[allow(clippy::type_complexity)]
struct RuntimeFn(
    Arc<dyn Fn(FrameworkExporter<'_>) -> Result<Cow<'static, str>, Error> + Send + Sync>,
);

impl fmt::Debug for RuntimeFn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RuntimeFn({:p})", self.0)
    }
}

/// Valibot language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Valibot {
    /// Custom header prepended to exported files.
    pub header: Cow<'static, str>,
    raw: Vec<Cow<'static, str>>,
    framework_runtime: Option<RuntimeFn>,
    framework_prelude: Cow<'static, str>,
    /// Output layout mode for generated Valibot TypeScript.
    pub layout: Layout,
}

impl Default for Valibot {
    fn default() -> Self {
        Self::new()
    }
}

impl Valibot {
    /// Construct a new exporter with default options configured.
    pub fn new() -> Self {
        Self {
            header: Cow::Borrowed(""),
            raw: Vec::new(),
            framework_runtime: None,
            framework_prelude: Cow::Borrowed("import * as v from \"valibot\";"),
            layout: Default::default(),
        }
    }

    /// Provide a prelude which is added to the start of all exported files.
    pub fn framework_prelude(mut self, prelude: impl Into<Cow<'static, str>>) -> Self {
        self.framework_prelude = prelude.into();
        self
    }

    /// Add runtime code exported as part of the bindings.
    pub fn framework_runtime(
        mut self,
        builder: impl Fn(FrameworkExporter<'_>) -> Result<Cow<'static, str>, Error>
        + Send
        + Sync
        + 'static,
    ) -> Self {
        self.framework_runtime = Some(RuntimeFn(Arc::new(builder)));
        self
    }

    /// Add raw TypeScript code to the generated bindings.
    pub fn with_raw(mut self, raw: impl Into<Cow<'static, str>>) -> Self {
        self.raw.push(raw.into());
        self
    }

    /// Configure a header for the file.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Configure bindings layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Export files into a single string.
    pub fn export(&self, types: &Types, format: impl Format) -> Result<String, Error> {
        let exporter = self.clone();
        let formatted_types = format_types(types, &format)?;
        let types = formatted_types.as_ref();

        if let Layout::Files = exporter.layout {
            return Err(Error::unable_to_export(exporter.layout));
        }

        let mut out = render_file_header(&exporter);

        let manually_exported_user_types = RefCell::new(HashSet::new());
        let mut runtime = Ok(Cow::default());
        if let Some(framework_runtime) = &exporter.framework_runtime {
            runtime = (framework_runtime.0)(FrameworkExporter {
                exporter: &exporter,
                format: Some(&format),
                manually_exported_user_types: &manually_exported_user_types,
                files_root_types: "",
                types,
            });
        }
        let runtime = render_runtime(&exporter, runtime?);

        if !runtime.is_empty() {
            out.push('\n');
            out.push_str(&runtime);
            out.push('\n');
        }

        render_types(
            &mut out,
            &exporter,
            types,
            "",
            &manually_exported_user_types.into_inner(),
            true,
        )?;

        Ok(out)
    }

    /// Export the types to a specific file/folder.
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        types: &Types,
        format: impl Format,
    ) -> Result<(), Error> {
        let exporter = self.clone();
        let formatted_types = format_types(types, &format)?;
        let types = formatted_types.as_ref();
        let path = path.as_ref();

        if exporter.layout != Layout::Files {
            let mut result = render_file_header(&exporter);

            let manually_exported_user_types = RefCell::new(HashSet::new());
            let mut runtime = Ok(Cow::default());
            if let Some(framework_runtime) = &exporter.framework_runtime {
                runtime = (framework_runtime.0)(FrameworkExporter {
                    exporter: &exporter,
                    format: Some(&format),
                    manually_exported_user_types: &manually_exported_user_types,
                    files_root_types: "",
                    types,
                });
            }
            let runtime = render_runtime(&exporter, runtime?);

            if !runtime.is_empty() {
                result.push('\n');
                result.push_str(&runtime);
                result.push('\n');
            }

            render_types(
                &mut result,
                &exporter,
                types,
                "",
                &manually_exported_user_types.into_inner(),
                true,
            )?;

            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, result)?;
            return Ok(());
        }

        fn export(
            exporter: &Valibot,
            types: &Types,
            module: &mut Module,
            manually_exported_root_types: &HashSet<(String, String)>,
            s: &mut String,
            path: &Path,
            files: &mut HashMap<PathBuf, String>,
        ) -> Result<bool, Error> {
            module.types.sort_by(|a, b| {
                a.name
                    .cmp(&b.name)
                    .then(a.module_path.cmp(&b.module_path))
                    .then(a.location.cmp(&b.location))
            });

            let module_types = module
                .types
                .iter()
                .copied()
                .filter(|ndt| {
                    !module.module_path.is_empty()
                        || !manually_exported_root_types.contains(&manual_export_identity(ndt))
                })
                .collect::<Vec<_>>();
            let (rendered_types_result, referenced_types) =
                references::with_module_path(module.module_path.as_ref(), || {
                    references::collect_references(|| {
                        let mut rendered = String::new();
                        let exports = render_flat_types(
                            &mut rendered,
                            exporter,
                            types,
                            module_types.into_iter(),
                            "",
                        )?;
                        Ok::<_, Error>((rendered, exports))
                    })
                });

            let (rendered_types, exports) = rendered_types_result?;

            let import_paths = referenced_types
                .into_iter()
                .filter_map(|r| {
                    types
                        .get(&r)
                        .map(|ndt| ndt.module_path.as_ref().to_string())
                })
                .filter(|module_path| module_path != module.module_path.as_ref())
                .collect::<BTreeSet<_>>();

            if !import_paths.is_empty() {
                s.push('\n');
                s.push_str(&module_import_block(
                    module.module_path.as_ref(),
                    &import_paths,
                ));
            }

            if !import_paths.is_empty() && !rendered_types.is_empty() {
                s.push('\n');
            }

            s.push_str(&rendered_types);

            for (name, module) in &mut module.children {
                if module.types.is_empty() && module.children.is_empty() {
                    continue;
                }

                // `index.ts` is reserved for root types and framework runtime.
                // Escape a top-level Rust `index` module, including its subtree,
                // so it cannot be silently overwritten by that root file.
                let file_name = if module.module_path == "index" {
                    "$index"
                } else {
                    name
                };
                let mut path = path.join(file_name);
                let mut out = render_file_header(exporter);
                let has_types = export(
                    exporter,
                    types,
                    module,
                    manually_exported_root_types,
                    &mut out,
                    &path,
                    files,
                )?;
                if has_types {
                    path.set_extension("ts");
                    files.insert(path, out);
                }
            }

            Ok(!exports.is_empty())
        }

        let mut files = HashMap::new();
        let mut runtime_path = path.join("index");
        runtime_path.set_extension("ts");

        let mut module_graph = build_module_graph(types.into_unsorted_iter());
        let mut root_types = String::new();
        export(
            &exporter,
            types,
            &mut module_graph,
            &HashSet::new(),
            &mut root_types,
            path,
            &mut files,
        )?;

        {
            let manually_exported_user_types = RefCell::new(HashSet::new());
            let mut runtime: Cow<'static, str> = Cow::default();
            let mut runtime_references = HashSet::new();
            if let Some(framework_runtime) = &exporter.framework_runtime {
                let (runtime_result, referenced_types) = references::with_module_path("", || {
                    references::collect_references(|| {
                        (framework_runtime.0)(FrameworkExporter {
                            exporter: &exporter,
                            format: Some(&format),
                            manually_exported_user_types: &manually_exported_user_types,
                            files_root_types: &root_types,
                            types,
                        })
                    })
                });
                runtime = runtime_result?;
                runtime_references = referenced_types;
            }
            let runtime = render_runtime(&exporter, runtime);

            let manually_exported_user_types = manually_exported_user_types.into_inner();
            if manually_exported_user_types
                .iter()
                .any(|(module_path, _)| module_path.is_empty())
            {
                root_types.clear();
                export(
                    &exporter,
                    types,
                    &mut module_graph,
                    &manually_exported_user_types,
                    &mut root_types,
                    path,
                    &mut files,
                )?;
            }

            let should_export_user_types = !root_types.is_empty();

            if !runtime.is_empty() || should_export_user_types {
                files.insert(runtime_path, {
                    let mut out = render_file_header(&exporter);
                    let mut body = String::new();

                    if !runtime.is_empty() {
                        body.push_str(&runtime);
                    }

                    if should_export_user_types {
                        if !body.is_empty() {
                            body.push('\n');
                        }
                        body.push_str(&root_types);
                    }

                    let import_paths = runtime_references
                        .into_iter()
                        .filter_map(|r| {
                            types
                                .get(&r)
                                .map(|ndt| ndt.module_path.as_ref().to_string())
                        })
                        .filter(|module_path| !module_path.is_empty())
                        .collect::<BTreeSet<_>>();

                    let import_paths = import_paths
                        .into_iter()
                        .filter(|module_path| {
                            !body.contains(&module_import_statement("", module_path))
                        })
                        .collect::<BTreeSet<_>>();

                    if !import_paths.is_empty() {
                        out.push('\n');
                        out.push_str(&module_import_block("", &import_paths));
                    }

                    if !body.is_empty() {
                        out.push('\n');
                        if !import_paths.is_empty() {
                            out.push('\n');
                        }
                        out.push_str(&body);
                    }

                    out
                });
            }
        }

        match path.metadata() {
            Ok(meta) if !meta.is_dir() => std::fs::remove_file(path).or_else(|source| {
                if source.kind() == std::io::ErrorKind::NotFound {
                    Ok(())
                } else {
                    Err(Error::remove_file(path.to_path_buf(), source))
                }
            })?,
            Ok(_) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::metadata(path.to_path_buf(), source));
            }
        }

        for (path, content) in &files {
            path.parent().map(std::fs::create_dir_all).transpose()?;
            std::fs::write(path, content)?;
        }

        cleanup_stale_files(path, &files)?;

        Ok(())
    }
}

fn format_types<'a>(types: &'a Types, format: &dyn Format) -> Result<Cow<'a, Types>, Error> {
    Ok(
        match format
            .map_types(types)
            .map_err(|err| Error::format("type graph formatter failed", err))?
        {
            Cow::Borrowed(_) => Cow::Borrowed(types),
            Cow::Owned(types) => Cow::Owned(types),
        },
    )
}

fn map_datatype_format(
    format: Option<&dyn Format>,
    types: &Types,
    dt: &DataType,
) -> Result<DataType, Error> {
    if matches!(dt, DataType::Generic(_)) {
        return Ok(dt.clone());
    }

    fn contains_generic_reference(dt: &DataType) -> bool {
        match dt {
            DataType::Primitive(_) => false,
            DataType::List(list) => contains_generic_reference(&list.ty),
            DataType::Map(map) => {
                contains_generic_reference(map.key_ty())
                    || contains_generic_reference(map.value_ty())
            }
            DataType::Nullable(inner) => contains_generic_reference(inner),
            DataType::Struct(strct) => fields_contain_generic(&strct.fields),
            DataType::Enum(enm) => enm
                .variants
                .iter()
                .any(|(_, variant)| fields_contain_generic(&variant.fields)),
            DataType::Tuple(tuple) => tuple.elements.iter().any(contains_generic_reference),
            DataType::Intersection(types) => types.iter().any(contains_generic_reference),
            DataType::Reference(Reference::Named(reference)) => match &reference.inner {
                specta::datatype::NamedReferenceType::Reference { generics, .. } => generics
                    .iter()
                    .any(|(_, generic)| contains_generic_reference(generic)),
                specta::datatype::NamedReferenceType::Inline { .. }
                | specta::datatype::NamedReferenceType::Recursive(_) => false,
            },
            DataType::Generic(_) => true,
            DataType::Reference(Reference::Opaque(_)) => false,
        }
    }

    fn fields_contain_generic(fields: &Fields) -> bool {
        match fields {
            Fields::Unit => false,
            Fields::Unnamed(fields) => fields
                .fields
                .iter()
                .filter_map(|field| field.ty.as_ref())
                .any(contains_generic_reference),
            Fields::Named(fields) => fields
                .fields
                .iter()
                .filter_map(|(_, field)| field.ty.as_ref())
                .any(contains_generic_reference),
        }
    }

    if contains_generic_reference(dt) {
        let Some(format) = format else {
            return map_datatype_format_children(None, types, dt.clone());
        };

        return match format.map_type(types, dt) {
            Ok(Cow::Borrowed(dt)) => map_datatype_format_children(Some(format), types, dt.clone()),
            Ok(Cow::Owned(dt)) => map_datatype_format_children(Some(format), types, dt),
            Err(err) if is_unresolved_generic_format_error(err.as_ref()) => {
                map_datatype_format_children(Some(format), types, dt.clone())
            }
            Err(err) => Err(Error::format("datatype formatter failed", err)),
        };
    }

    let Some(format) = format else {
        return Ok(dt.clone());
    };

    let mapped = format
        .map_type(types, dt)
        .map_err(|err| Error::format("datatype formatter failed", err))?;

    match mapped {
        Cow::Borrowed(dt) => map_datatype_format_children(Some(format), types, dt.clone()),
        Cow::Owned(dt) => map_datatype_format_children(Some(format), types, dt),
    }
}

fn is_unresolved_generic_format_error(err: &(dyn std::error::Error + 'static)) -> bool {
    // `Format` erases its concrete error type, so matching the formatter's stable
    // message is the narrowest fallback available before child substitution.
    err.to_string().contains("Unresolved generic reference")
}

fn map_datatype_format_children(
    format: Option<&dyn Format>,
    types: &Types,
    mut dt: DataType,
) -> Result<DataType, Error> {
    match &mut dt {
        DataType::Primitive(_) => {}
        DataType::List(list) => {
            *list.ty = map_datatype_format(format, types, &list.ty)?;
        }
        DataType::Map(map) => {
            let key = map_datatype_format(format, types, map.key_ty())?;
            let value = map_datatype_format(format, types, map.value_ty())?;
            map.set_key_ty(key);
            map.set_value_ty(value);
        }
        DataType::Nullable(inner) => {
            **inner = map_datatype_format(format, types, inner)?;
        }
        DataType::Struct(strct) => map_datatype_fields(format, types, &mut strct.fields)?,
        DataType::Enum(enm) => {
            for (_, variant) in &mut enm.variants {
                map_datatype_fields(format, types, &mut variant.fields)?;
            }
        }
        DataType::Tuple(tuple) => {
            for element in &mut tuple.elements {
                *element = map_datatype_format(format, types, element)?;
            }
        }
        DataType::Intersection(intersection) => {
            for element in intersection {
                *element = map_datatype_format(format, types, element)?;
            }
        }
        DataType::Reference(Reference::Named(reference)) => {
            if let specta::datatype::NamedReferenceType::Inline { dt, .. } = &mut reference.inner {
                **dt = map_datatype_format(format, types, dt)?;
            }

            if let specta::datatype::NamedReferenceType::Reference { generics, .. } =
                &mut reference.inner
            {
                for (_, generic) in generics {
                    *generic = map_datatype_format(format, types, generic)?;
                }
            }
        }
        DataType::Reference(Reference::Opaque(_)) | DataType::Generic(_) => {}
    }

    Ok(dt)
}

fn map_datatype_fields(
    format: Option<&dyn Format>,
    types: &Types,
    fields: &mut Fields,
) -> Result<(), Error> {
    match fields {
        Fields::Unit => {}
        Fields::Unnamed(unnamed) => {
            for field in &mut unnamed.fields {
                if let Some(ty) = field.ty.as_mut() {
                    *ty = map_datatype_format(format, types, ty)?;
                }
            }
        }
        Fields::Named(named) => {
            for (_, field) in &mut named.fields {
                if let Some(ty) = field.ty.as_mut() {
                    *ty = map_datatype_format(format, types, ty)?;
                }
            }
        }
    }

    Ok(())
}

fn map_named_datatype_format(
    format: Option<&dyn Format>,
    types: &Types,
    ndt: &NamedDataType,
) -> Result<NamedDataType, Error> {
    let mut mapped = ndt.clone();
    mapped.ty = ndt
        .ty
        .clone()
        .map(|ty| map_datatype_format_children(format, types, ty))
        .transpose()?;
    Ok(mapped)
}

impl AsRef<Valibot> for Valibot {
    fn as_ref(&self) -> &Valibot {
        self
    }
}

impl AsMut<Valibot> for Valibot {
    fn as_mut(&mut self) -> &mut Valibot {
        self
    }
}

/// Reference to the Valibot exporter for framework callbacks.
pub struct FrameworkExporter<'a> {
    exporter: &'a Valibot,
    format: Option<&'a dyn Format>,
    manually_exported_user_types: &'a RefCell<HashSet<(String, String)>>,
    files_root_types: &'a str,
    /// Collected types currently being exported.
    pub types: &'a Types,
}

impl fmt::Debug for FrameworkExporter<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.exporter.fmt(f)
    }
}

impl AsRef<Valibot> for FrameworkExporter<'_> {
    fn as_ref(&self) -> &Valibot {
        self.exporter
    }
}

impl Deref for FrameworkExporter<'_> {
    type Target = Valibot;

    fn deref(&self) -> &Self::Target {
        self.exporter
    }
}

impl FrameworkExporter<'_> {
    /// Render the types within [`Types`](specta::Types).
    pub fn render_types(&mut self) -> Result<Cow<'static, str>, Error> {
        let mut s = String::new();
        render_types(
            &mut s,
            self.exporter,
            self.types,
            self.files_root_types,
            &HashSet::new(),
            true,
        )?;
        self.manually_exported_user_types
            .borrow_mut()
            .extend(self.types.into_unsorted_iter().map(manual_export_identity));
        Ok(Cow::Owned(s))
    }

    /// [primitives::inline]
    pub fn inline(&self, dt: &DataType) -> Result<String, Error> {
        let mapped = map_datatype_format(self.format, self.types, dt)?;
        primitives::inline(self, self.types, &mapped)
    }

    /// [primitives::reference]
    pub fn reference(&self, r: &Reference) -> Result<String, Error> {
        let mapped = map_datatype_format(self.format, self.types, &DataType::Reference(r.clone()))?;
        match mapped {
            DataType::Reference(reference) => primitives::reference(self, self.types, &reference),
            dt => primitives::inline(self, self.types, &dt),
        }
    }

    /// [primitives::export]
    pub fn export<'a>(
        &self,
        ndts: impl Iterator<Item = &'a NamedDataType>,
        indent: &'a str,
    ) -> Result<String, Error> {
        let ndts = ndts.collect::<Vec<_>>();
        let mapped = ndts
            .iter()
            .map(|ndt| map_named_datatype_format(self.format, self.types, ndt))
            .collect::<Result<Vec<_>, _>>()?;
        let rendered = if self.layout == Layout::Namespaces {
            render_manual_namespace_types(
                self,
                self.types,
                &mapped,
                indent,
                &self.manually_exported_user_types.borrow(),
            )?
        } else {
            primitives::export(self, self.types, mapped.iter(), indent)?
        };
        self.manually_exported_user_types.borrow_mut().extend(
            ndts.into_iter()
                .filter(|ndt| ndt.ty.is_some())
                .map(manual_export_identity),
        );
        Ok(rendered)
    }
}

fn manual_export_identity(ndt: &NamedDataType) -> (String, String) {
    (ndt.module_path.to_string(), ndt.name.to_string())
}

fn render_manual_namespace_types(
    exporter: &Valibot,
    types: &Types,
    ndts: &[NamedDataType],
    indent: &str,
    already_exported: &HashSet<(String, String)>,
) -> Result<String, Error> {
    let mut modules = BTreeMap::<&str, Vec<&NamedDataType>>::new();
    for ndt in ndts.iter().filter(|ndt| ndt.ty.is_some()) {
        modules
            .entry(ndt.module_path.as_ref())
            .or_default()
            .push(ndt);
    }

    let mut out = String::new();
    let mut emitted_top_modules = already_exported
        .iter()
        .filter_map(|(module_path, _)| module_path.split("::").next())
        .filter(|module| !module.is_empty())
        .map(str::to_string)
        .collect::<HashSet<_>>();
    for (module_path, ndts) in modules {
        out.push_str(indent);
        out.push_str("namespace $s$ {\n");

        let segments = module_path
            .split("::")
            .filter(|segment| !segment.is_empty())
            .collect::<Vec<_>>();
        for (depth, segment) in segments.iter().enumerate() {
            out.push_str(indent);
            out.push_str(&"\t".repeat(depth + 1));
            out.push_str("export namespace ");
            out.push_str(&namespace_segment(segment));
            out.push_str(" {\n");
        }

        let content_indent = format!("{indent}{}", "\t".repeat(segments.len() + 1));
        out.push_str(&primitives::export(
            exporter,
            types,
            ndts.iter().copied(),
            &content_indent,
        )?);
        if !out.ends_with('\n') {
            out.push('\n');
        }

        for depth in (0..segments.len()).rev() {
            out.push_str(indent);
            out.push_str(&"\t".repeat(depth + 1));
            out.push_str("}\n");
        }
        out.push_str(indent);
        out.push_str("}\n");

        if module_path.is_empty() {
            for ndt in ndts {
                if already_exported.contains(&manual_export_identity(ndt)) {
                    continue;
                }
                out.push_str(indent);
                out.push_str("export import ");
                out.push_str(&ndt.name);
                out.push_str(" = $s$.");
                out.push_str(&ndt.name);
                out.push_str(";\n");
                out.push_str(indent);
                out.push_str("export import ");
                out.push_str(&ndt.name);
                out.push_str("Schema = $s$.");
                out.push_str(&ndt.name);
                out.push_str("Schema;\n");
            }
        } else {
            let top_module = module_path.split("::").next().unwrap_or_default();
            if emitted_top_modules.insert(top_module.to_string()) {
                let top_module = namespace_segment(top_module);
                out.push_str(indent);
                out.push_str("export import ");
                out.push_str(&top_module);
                out.push_str(" = $s$.");
                out.push_str(&top_module);
                out.push_str(";\n");
            }
        }
    }

    Ok(out)
}

struct Module<'a> {
    types: Vec<&'a NamedDataType>,
    children: BTreeMap<&'a str, Module<'a>>,
    module_path: Cow<'static, str>,
}

fn build_module_graph<'a>(types: impl Iterator<Item = &'a NamedDataType>) -> Module<'a> {
    types.fold(
        Module {
            types: Default::default(),
            children: Default::default(),
            module_path: Default::default(),
        },
        |mut ns, ndt| {
            let path = &ndt.module_path;

            if path.is_empty() {
                ns.types.push(ndt);
            } else {
                let mut current = &mut ns;
                let mut current_path = String::new();
                for segment in path.split("::") {
                    if !current_path.is_empty() {
                        current_path.push_str("::");
                    }
                    current_path.push_str(segment);

                    current = current.children.entry(segment).or_insert_with(|| Module {
                        types: Default::default(),
                        children: Default::default(),
                        module_path: current_path.clone().into(),
                    });
                }

                current.types.push(ndt);
            }

            ns
        },
    )
}

fn render_file_header(exporter: &Valibot) -> String {
    let mut out = exporter.header.to_string();
    if !exporter.header.is_empty() {
        out.push('\n');
    }

    out.push_str(&exporter.framework_prelude);
    if !exporter.framework_prelude.is_empty() {
        out.push('\n');
    }
    out.push_str(GENERATED_FILE_MARKER);
    out.push('\n');
    out.push_str(runtime_helpers());
    out.push('\n');

    out
}

fn render_runtime(exporter: &Valibot, runtime: Cow<'static, str>) -> String {
    (!runtime.is_empty())
        .then_some(runtime.as_ref())
        .into_iter()
        .chain(
            exporter
                .raw
                .iter()
                .map(Cow::as_ref)
                .filter(|raw| !raw.is_empty()),
        )
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_types(
    s: &mut String,
    exporter: &Valibot,
    types: &Types,
    files_user_types: &str,
    manually_exported_user_types: &HashSet<(String, String)>,
    render_namespace_reexports: bool,
) -> Result<(), Error> {
    match exporter.layout {
        Layout::Namespaces => {
            fn has_renderable_content(module: &Module<'_>) -> bool {
                module.types.iter().any(|ndt| ndt.ty.is_some())
                    || module.children.values().any(has_renderable_content)
            }

            fn validate_namespace_scopes(module: &Module<'_>) -> Result<(), Error> {
                let mut exports = HashSet::new();
                for ndt in module.types.iter().filter(|ndt| ndt.ty.is_some()) {
                    for name in [ndt.name.to_string(), format!("{}Schema", ndt.name)] {
                        if !exports.insert(name.clone()) {
                            return Err(Error::duplicate_export_name(name));
                        }
                    }
                }
                for (name, child) in module
                    .children
                    .iter()
                    .filter(|(_, child)| has_renderable_content(child))
                {
                    let name = namespace_segment(name).into_owned();
                    if !exports.insert(name.clone()) {
                        return Err(Error::duplicate_export_name(name));
                    }
                    validate_namespace_scopes(child)?;
                }
                Ok(())
            }

            fn validate_namespace_reexports(module: &Module<'_>) -> Result<(), Error> {
                let mut exports = HashSet::new();
                for name in module
                    .children
                    .iter()
                    .filter_map(|(name, module)| has_renderable_content(module).then_some(*name))
                    .chain(
                        module
                            .types
                            .iter()
                            .filter(|ndt| ndt.ty.is_some())
                            .map(|ndt| ndt.name.as_ref()),
                    )
                    .map(namespace_segment)
                    .chain(
                        module
                            .types
                            .iter()
                            .filter(|ndt| ndt.ty.is_some())
                            .map(|ndt| Cow::Owned(format!("{}Schema", ndt.name))),
                    )
                {
                    if !exports.insert(name.to_string()) {
                        return Err(Error::duplicate_export_name(name.into_owned()));
                    }
                }
                Ok(())
            }

            fn export<'a>(
                exporter: &Valibot,
                types: &Types,
                s: &mut String,
                module: impl ExactSizeIterator<Item = (&'a &'a str, &'a mut Module<'a>)>,
                depth: usize,
            ) -> Result<(), Error> {
                let namespace_indent = "\t".repeat(depth);
                let content_indent = "\t".repeat(depth + 1);

                for (name, module) in module {
                    if !has_renderable_content(module) {
                        continue;
                    }

                    s.push('\n');
                    s.push_str(&namespace_indent);
                    if depth != 0 && *name != "$s$" {
                        s.push_str("export ");
                    }
                    s.push_str("namespace ");
                    s.push_str(&namespace_segment(name));
                    s.push_str(" {\n");

                    module.types.sort_by(|a, b| {
                        a.name
                            .cmp(&b.name)
                            .then(a.module_path.cmp(&b.module_path))
                            .then(a.location.cmp(&b.location))
                    });
                    render_flat_types(
                        s,
                        exporter,
                        types,
                        module.types.iter().copied(),
                        &content_indent,
                    )?;
                    export(exporter, types, s, module.children.iter_mut(), depth + 1)?;

                    s.push_str(&namespace_indent);
                    s.push_str("}\n");
                }
                Ok(())
            }

            let complete_module = build_module_graph(types.into_unsorted_iter());
            validate_namespace_scopes(&complete_module)?;
            validate_namespace_reexports(&complete_module)?;

            let mut module = build_module_graph(types.into_unsorted_iter().filter(|ndt| {
                !manually_exported_user_types.contains(&manual_export_identity(ndt))
            }));
            let mut reexports = String::new();
            let mut reexport_names = HashSet::new();
            let manually_exported_top_modules = manually_exported_user_types
                .iter()
                .filter_map(|(module_path, _)| module_path.split("::").next())
                .filter(|module| !module.is_empty())
                .collect::<HashSet<_>>();
            for name in complete_module
                .children
                .iter()
                .filter_map(|(name, module)| {
                    (has_renderable_content(module)
                        && !manually_exported_top_modules.contains(name))
                    .then_some(*name)
                })
                .chain(
                    complete_module
                        .types
                        .iter()
                        .filter(|ndt| {
                            ndt.ty.is_some()
                                && !manually_exported_user_types
                                    .contains(&manual_export_identity(ndt))
                        })
                        .map(|ndt| ndt.name.as_ref()),
                )
            {
                let name = namespace_segment(name);
                if !reexport_names.insert(name.to_string()) {
                    return Err(Error::duplicate_export_name(name.into_owned()));
                }
                reexports.push_str("export import ");
                reexports.push_str(&name);
                reexports.push_str(" = $s$.");
                reexports.push_str(&name);
                reexports.push_str(";\n");
            }
            for ndt in complete_module.types.iter().filter(|ndt| {
                ndt.ty.is_some()
                    && !manually_exported_user_types.contains(&manual_export_identity(ndt))
            }) {
                let schema_name = format!("{}Schema", ndt.name);
                if !reexport_names.insert(schema_name.clone()) {
                    return Err(Error::duplicate_export_name(schema_name));
                }
                reexports.push_str("export import ");
                reexports.push_str(&ndt.name);
                reexports.push_str("Schema = $s$.");
                reexports.push_str(&ndt.name);
                reexports.push_str("Schema;\n");
            }

            export(exporter, types, s, [(&"$s$", &mut module)].into_iter(), 0)?;
            if render_namespace_reexports {
                s.push_str(&reexports);
            }
        }
        Layout::FlatFile | Layout::ModulePrefixedName => {
            validate_flat_type_names(exporter, types.into_sorted_iter())?;
            let remaining_types = types
                .into_sorted_iter()
                .filter(|ndt| !manually_exported_user_types.contains(&manual_export_identity(ndt)))
                .collect::<Vec<_>>();
            render_flat_types(s, exporter, types, remaining_types.into_iter(), "")?;
        }
        Layout::Files => {
            if !files_user_types.is_empty() {
                s.push_str(files_user_types);
            }
        }
    }

    Ok(())
}

fn validate_flat_type_names<'a>(
    exporter: &Valibot,
    ndts: impl Iterator<Item = &'a NamedDataType>,
) -> Result<(), Error> {
    let mut exports = HashMap::new();
    for ndt in ndts.filter(|ndt| ndt.ty.is_some()) {
        let export_name = primitives::exported_type_name(exporter, ndt);
        if let Some(other) = exports.insert(export_name.to_string(), ndt.location) {
            return Err(Error::duplicate_type_name(export_name, ndt.location, other));
        }
    }
    Ok(())
}

fn render_flat_types<'a>(
    s: &mut String,
    exporter: &Valibot,
    types: &Types,
    ndts: impl ExactSizeIterator<Item = &'a NamedDataType>,
    indent: &str,
) -> Result<HashMap<String, std::panic::Location<'static>>, Error> {
    let mut exports = HashMap::with_capacity(ndts.len());

    let ndts = ndts
        .filter(|ndt| ndt.ty.is_some())
        .map(|ndt| {
            let export_name = primitives::exported_type_name(exporter, ndt);
            if let Some(other) = exports.insert(export_name.to_string(), ndt.location) {
                return Err(Error::duplicate_type_name(export_name, ndt.location, other));
            }
            Ok(ndt)
        })
        .collect::<Result<Vec<_>, _>>()?;

    let mut type_render_stack = Vec::new();
    primitives::export_internal(
        s,
        exporter,
        types,
        ndts.into_iter(),
        indent,
        &mut type_render_stack,
    )?;

    Ok(exports)
}

fn collect_existing_files(root: &Path) -> Result<HashSet<PathBuf>, Error> {
    if !root.exists() {
        return Ok(HashSet::new());
    }

    let mut files = HashSet::new();
    let entries =
        std::fs::read_dir(root).map_err(|source| Error::read_dir(root.to_path_buf(), source))?;
    for entry in entries {
        let entry = entry.map_err(|source| Error::read_dir(root.to_path_buf(), source))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| Error::metadata(path.clone(), source))?;

        if file_type.is_symlink() {
            continue;
        }

        if file_type.is_dir() {
            files.extend(collect_existing_files(&path)?);
        } else if matches!(path.extension().and_then(|e| e.to_str()), Some("ts")) {
            files.insert(path);
        }
    }

    Ok(files)
}

fn is_generated_specta_file(path: &Path) -> Result<bool, Error> {
    match std::fs::read_to_string(path) {
        Ok(contents) => Ok(contents.contains(GENERATED_FILE_MARKER)),
        Err(err) if err.kind() == std::io::ErrorKind::InvalidData => Ok(false),
        Err(source) => Err(Error::from(source)),
    }
}

fn remove_empty_dirs(path: &Path, root: &Path) -> Result<(), Error> {
    let entries =
        std::fs::read_dir(path).map_err(|source| Error::read_dir(path.to_path_buf(), source))?;
    for entry in entries {
        let entry = entry.map_err(|source| Error::read_dir(path.to_path_buf(), source))?;
        let entry_path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| Error::metadata(entry_path.clone(), source))?;
        if file_type.is_symlink() {
            continue;
        }
        if file_type.is_dir() {
            remove_empty_dirs(&entry_path, root)?;
        }
    }

    let is_empty = path
        .read_dir()
        .map_err(|source| Error::read_dir(path.to_path_buf(), source))?
        .next()
        .is_none();

    if path != root && is_empty {
        match std::fs::remove_dir(path) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::remove_dir(path.to_path_buf(), source));
            }
        }
    }
    Ok(())
}

fn cleanup_stale_files(root: &Path, current_files: &HashMap<PathBuf, String>) -> Result<(), Error> {
    for path in collect_existing_files(root)? {
        if current_files.contains_key(&path) || !is_generated_specta_file(&path)? {
            continue;
        }

        std::fs::remove_file(&path).or_else(|source| {
            if source.kind() == std::io::ErrorKind::NotFound {
                Ok(())
            } else {
                Err(Error::remove_file(path.clone(), source))
            }
        })?;
    }

    if root.exists() {
        remove_empty_dirs(root, root)?;
    }

    Ok(())
}

pub(crate) fn module_alias(module_path: &str) -> String {
    if module_path.is_empty() {
        "$root".to_string()
    } else {
        let alias = module_path.split("::").collect::<Vec<_>>().join("$");
        typescript_identifier(&alias).into_owned()
    }
}

pub(crate) fn namespace_module_path(module_path: &str) -> String {
    module_path
        .split("::")
        .filter(|segment| !segment.is_empty())
        .map(namespace_segment)
        .collect::<Vec<_>>()
        .join(".")
}

fn namespace_segment(segment: &str) -> Cow<'_, str> {
    typescript_identifier(segment.strip_prefix("r#").unwrap_or(segment))
}

fn typescript_identifier(identifier: &str) -> Cow<'_, str> {
    let mut chars = identifier.chars();
    let valid = chars
        .next()
        .is_some_and(|ch| ch.is_alphabetic() || ch == '_' || ch == '$')
        && chars.all(|ch| ch.is_alphanumeric() || ch == '_' || ch == '$');
    if valid && !RESERVED_TYPE_NAMES.contains(&identifier) {
        return Cow::Borrowed(identifier);
    }

    let mut sanitized = String::from("$");
    for ch in identifier.chars() {
        sanitized.push(if ch.is_alphanumeric() || ch == '_' || ch == '$' {
            ch
        } else {
            '_'
        });
    }
    Cow::Owned(sanitized)
}

fn module_import_statement(from_module_path: &str, to_module_path: &str) -> String {
    format!(
        "import * as {} from \"{}\";",
        module_alias(to_module_path),
        module_import_path(from_module_path, to_module_path)
    )
}

fn module_import_block(from_module_path: &str, import_paths: &BTreeSet<String>) -> String {
    import_paths
        .iter()
        .map(|module_path| module_import_statement(from_module_path, module_path))
        .collect::<Vec<_>>()
        .join("\n")
}

fn module_import_path(from_module_path: &str, to_module_path: &str) -> String {
    fn module_file_segments(module_path: &str) -> Vec<String> {
        if module_path.is_empty() {
            vec!["index".to_string()]
        } else {
            module_path
                .split("::")
                .enumerate()
                .map(|(index, segment)| {
                    if index == 0 && segment == "index" {
                        "$index".to_string()
                    } else {
                        segment.to_string()
                    }
                })
                .collect()
        }
    }

    let from_file_segments = module_file_segments(from_module_path);
    let from_dir_segments = &from_file_segments[..from_file_segments.len() - 1];
    let to_file_segments = module_file_segments(to_module_path);

    let to_dir_segments = &to_file_segments[..to_file_segments.len() - 1];
    let shared = from_dir_segments
        .iter()
        .zip(to_dir_segments.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let mut relative_parts = Vec::new();
    relative_parts.extend(std::iter::repeat_n(
        "..",
        from_dir_segments.len().saturating_sub(shared),
    ));
    relative_parts.extend(to_file_segments.iter().skip(shared).map(String::as_str));

    if relative_parts
        .first()
        .is_none_or(|v| *v != "." && *v != "..")
    {
        relative_parts.insert(0, ".");
    }

    relative_parts.join("/")
}
