use std::{
    borrow::Cow,
    collections::{BTreeMap, HashMap, HashSet},
    fmt,
    path::{Path, PathBuf},
    sync::Arc,
};

use specta::{
    Format, Types,
    datatype::{
        DataType, Deprecated, Field, Fields, NamedDataType, NamedReference, NamedReferenceType,
        OpaqueReference, Primitive, Reference,
    },
};

use crate::Error;

const GENERATED_MARKER: &str =
    "// This file has been generated by Specta. Do not edit this file manually.";

/// Controls the structure of generated Rust source.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Layout {
    /// Place every declaration in one flat module.
    #[default]
    FlatFile,
    /// Recreate source module paths as nested `pub mod` blocks.
    Modules,
    /// Recreate source module paths as nested `pub mod` blocks.
    ///
    /// This spelling mirrors `specta_typescript::Layout::Namespaces`.
    Namespaces,
    /// Prefix each type name with its source module path and keep one flat module.
    ModulePrefixedName,
    /// Write a root `mod.rs` plus conventional child module files.
    Files,
}

impl fmt::Display for Layout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

/// Rust language exporter.
#[derive(Clone)]
#[non_exhaustive]
pub struct Rust {
    /// Content written before generated declarations.
    pub header: Cow<'static, str>,
    /// Generated source layout.
    pub layout: Layout,
    raw: Vec<Cow<'static, str>>,
    derives: Vec<Cow<'static, str>>,
    attributes: Vec<Cow<'static, str>>,
    opaque_renderer: Option<OpaqueRenderer>,
}

#[derive(Clone)]
struct OpaqueRenderer(
    Arc<dyn Fn(&OpaqueReference) -> Option<Cow<'static, str>> + Send + Sync + 'static>,
);

impl fmt::Debug for OpaqueRenderer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "OpaqueRenderer({:p})", self.0)
    }
}

impl fmt::Debug for Rust {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Rust")
            .field("header", &self.header)
            .field("layout", &self.layout)
            .field("raw", &self.raw)
            .field("derives", &self.derives)
            .field("attributes", &self.attributes)
            .field("opaque_renderer", &self.opaque_renderer)
            .finish()
    }
}

impl Default for Rust {
    fn default() -> Self {
        Self {
            header: Cow::Borrowed(""),
            layout: Layout::FlatFile,
            raw: Vec::new(),
            derives: Vec::new(),
            attributes: Vec::new(),
            opaque_renderer: None,
        }
    }
}

impl Rust {
    /// Construct an exporter with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Configure content written before generated declarations.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Configure the generated source layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Append raw Rust source after generated declarations.
    pub fn with_raw(mut self, raw: impl Into<Cow<'static, str>>) -> Self {
        self.raw.push(raw.into());
        self
    }

    /// Add a derive to every generated struct and enum.
    ///
    /// Pass a path without the surrounding attribute, for example `Debug` or
    /// `serde::Serialize`.
    pub fn derive(mut self, derive: impl Into<Cow<'static, str>>) -> Self {
        self.derives.push(derive.into());
        self
    }

    /// Add a raw outer attribute to every generated declaration.
    ///
    /// Pass the complete attribute, for example `#[non_exhaustive]`.
    pub fn attribute(mut self, attribute: impl Into<Cow<'static, str>>) -> Self {
        self.attributes.push(attribute.into());
        self
    }

    /// Configure a renderer for exporter-specific opaque references.
    ///
    /// Return `None` to retain the unsupported-opaque error for a value.
    pub fn opaque_type(
        mut self,
        renderer: impl Fn(&OpaqueReference) -> Option<Cow<'static, str>> + Send + Sync + 'static,
    ) -> Self {
        self.opaque_renderer = Some(OpaqueRenderer(Arc::new(renderer)));
        self
    }

    /// Render a datatype as a Rust type expression using this configuration.
    pub fn inline(
        &self,
        types: &Types,
        ty: &DataType,
        format: impl Format,
    ) -> Result<String, Error> {
        let formatted = format
            .map_types(types)
            .map_err(|source| Error::format("type graph formatter failed", "<inline>", source))?;
        let types = formatted.as_ref();
        let ty = map_datatype(Some(&format), types, ty, "<inline>")?;
        render_datatype(self, None, types, &ty, "<inline>")
    }

    /// Render a reference as a Rust type expression using this configuration.
    pub fn reference(
        &self,
        types: &Types,
        reference: &Reference,
        format: impl Format,
    ) -> Result<String, Error> {
        self.inline(types, &DataType::Reference(reference.clone()), format)
    }

    /// Export the provided types into a Rust source string.
    ///
    /// [`Layout::Files`] requires [`Self::export_to`].
    pub fn export(&self, types: &Types, format: impl Format) -> Result<String, Error> {
        if self.layout == Layout::Files {
            return Err(Error::ExportRequiresExportTo(self.layout));
        }

        let formatted = format
            .map_types(types)
            .map_err(|source| Error::format("type graph formatter failed", "", source))?;
        let types = formatted.as_ref();
        validate_names(self, types)?;

        let mut out = render_header(self);
        match self.layout {
            Layout::FlatFile | Layout::ModulePrefixedName => {
                for ndt in types.into_sorted_iter() {
                    render_named(&mut out, self, Some(&format), types, ndt, 0)?;
                }
            }
            Layout::Modules | Layout::Namespaces => {
                render_modules(&mut out, self, Some(&format), types)?
            }
            Layout::Files => unreachable!("handled above"),
        }
        render_raw(&mut out, self);
        Ok(out)
    }

    /// Export types to a file, or to a directory for [`Layout::Files`].
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        types: &Types,
        format: impl Format,
    ) -> Result<(), Error> {
        let path = path.as_ref();
        if self.layout != Layout::Files {
            let source = self.export(types, format)?;
            create_parent(path)?;
            return std::fs::write(path, source)
                .map_err(|source| Error::io("write generated file", path, source));
        }

        let formatted = format
            .map_types(types)
            .map_err(|source| Error::format("type graph formatter failed", "", source))?;
        let types = formatted.as_ref();
        validate_names(self, types)?;
        export_files(self, path, Some(&format), types)
    }
}

fn render_header(exporter: &Rust) -> String {
    let mut out = format!("{GENERATED_MARKER}\n");
    if !exporter.header.is_empty() {
        out.push_str(exporter.header.trim_end());
        out.push('\n');
    }
    out.push('\n');
    out
}

fn render_raw(out: &mut String, exporter: &Rust) {
    for raw in exporter.raw.iter().filter(|raw| !raw.is_empty()) {
        if !out.is_empty() && !out.ends_with("\n\n") {
            out.push('\n');
        }
        out.push_str(raw);
        if !out.ends_with('\n') {
            out.push('\n');
        }
    }
}

fn render_named(
    out: &mut String,
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    ndt: &NamedDataType,
    depth: usize,
) -> Result<(), Error> {
    let mut ndt = ndt.clone();
    let ndt_path = rust_path(&ndt);
    for generic in ndt.generics.to_mut() {
        if let Some(default) = &generic.default {
            generic.default = Some(map_datatype(
                format,
                types,
                default,
                &format!("{ndt_path}.<generic:{}>", generic.name),
            )?);
        }
    }
    let ndt = &ndt;
    let Some(ty) = &ndt.ty else {
        return Ok(());
    };
    let ty = map_datatype_children(format, types, ty.clone(), &rust_path(ndt))?;
    for generic in ndt.generics.iter() {
        if !datatype_uses_generic(&ty, &generic.name) {
            return Err(Error::UnusedGeneric {
                path: rust_path(ndt),
                name: generic.name.to_string(),
            });
        }
    }
    render_docs(out, &ndt.docs, depth);
    render_deprecated(out, ndt.deprecated.as_ref(), depth);
    render_name_allow(out, depth);
    for attribute in &exporter.attributes {
        line(out, depth, attribute);
    }

    let name = exported_name(exporter, ndt)?;
    match &ty {
        DataType::Struct(strct) => {
            render_derives(out, exporter, depth);
            render_struct(out, exporter, None, types, &name, ndt, &strct.fields, depth)?;
        }
        DataType::Enum(enm) => {
            render_derives(out, exporter, depth);
            render_enum(out, exporter, None, types, &name, ndt, enm, depth)?;
        }
        ty => {
            let generics = render_generic_definitions(exporter, None, types, ndt)?;
            let value = render_datatype(exporter, None, types, ty, &rust_path(ndt))?;
            line(out, depth, &format!("pub type {name}{generics} = {value};"));
        }
    }
    out.push('\n');
    Ok(())
}

fn render_struct(
    out: &mut String,
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    name: &str,
    ndt: &NamedDataType,
    fields: &Fields,
    depth: usize,
) -> Result<(), Error> {
    let generics = render_generic_definitions(exporter, format, types, ndt)?;
    match fields {
        Fields::Unit => line(out, depth, &format!("pub struct {name}{generics};")),
        Fields::Unnamed(fields) => {
            line(out, depth, &format!("pub struct {name}{generics}("));
            for (index, field) in fields.fields.iter().enumerate() {
                let Some(ty) = &field.ty else { continue };
                render_docs(out, &field.docs, depth + 1);
                render_deprecated(out, field.deprecated.as_ref(), depth + 1);
                let path = format!("{}.{index}", rust_path(ndt));
                let ty = render_field_type(exporter, format, types, field, ty, &path)?;
                line(out, depth + 1, &format!("pub {ty},"));
            }
            line(out, depth, ");");
        }
        Fields::Named(fields) => {
            line(out, depth, &format!("pub struct {name}{generics} {{"));
            for (field_name, field) in &fields.fields {
                let Some(ty) = &field.ty else { continue };
                render_docs(out, &field.docs, depth + 1);
                render_deprecated(out, field.deprecated.as_ref(), depth + 1);
                let ident = identifier(field_name, &format!("{}.{}", rust_path(ndt), field_name))?;
                let ty = render_field_type(
                    exporter,
                    format,
                    types,
                    field,
                    ty,
                    &format!("{}.{}", rust_path(ndt), field_name),
                )?;
                line(out, depth + 1, &format!("pub {ident}: {ty},"));
            }
            line(out, depth, "}");
        }
    }
    Ok(())
}

fn render_enum(
    out: &mut String,
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    name: &str,
    ndt: &NamedDataType,
    enm: &specta::datatype::Enum,
    depth: usize,
) -> Result<(), Error> {
    let generics = render_generic_definitions(exporter, format, types, ndt)?;
    line(out, depth, &format!("pub enum {name}{generics} {{"));
    for (variant_name, variant) in enm.variants.iter().filter(|(_, variant)| !variant.skip) {
        let variant_path = format!("{}.{}", rust_path(ndt), variant_name);
        let variant_name = identifier(variant_name, &variant_path)?;
        render_docs(out, &variant.docs, depth + 1);
        render_deprecated(out, variant.deprecated.as_ref(), depth + 1);
        match &variant.fields {
            Fields::Unit => line(out, depth + 1, &format!("{variant_name},")),
            Fields::Unnamed(fields)
                if enm
                    .attributes
                    .contains_key("specta_serde:enum_repr_rewritten")
                    && is_singleton_unit_enum_field(fields) =>
            {
                line(out, depth + 1, &format!("{variant_name},"));
            }
            Fields::Unnamed(fields) => {
                line(out, depth + 1, &format!("{variant_name}("));
                for (index, field) in fields.fields.iter().enumerate() {
                    let Some(ty) = &field.ty else { continue };
                    render_docs(out, &field.docs, depth + 2);
                    render_deprecated(out, field.deprecated.as_ref(), depth + 2);
                    let ty = render_field_type(
                        exporter,
                        format,
                        types,
                        field,
                        ty,
                        &format!("{variant_path}.{index}"),
                    )?;
                    line(out, depth + 2, &format!("{ty},"));
                }
                line(out, depth + 1, "),");
            }
            Fields::Named(fields) => {
                line(out, depth + 1, &format!("{variant_name} {{"));
                for (field_name, field) in &fields.fields {
                    let Some(ty) = &field.ty else { continue };
                    render_docs(out, &field.docs, depth + 2);
                    render_deprecated(out, field.deprecated.as_ref(), depth + 2);
                    let path = format!("{variant_path}.{field_name}");
                    let field_name = identifier(field_name, &path)?;
                    let ty = render_field_type(exporter, format, types, field, ty, &path)?;
                    line(out, depth + 2, &format!("{field_name}: {ty},"));
                }
                line(out, depth + 1, "},");
            }
        }
    }
    line(out, depth, "}");
    Ok(())
}

fn is_singleton_unit_enum_field(fields: &specta::datatype::UnnamedFields) -> bool {
    matches!(
        fields.fields.as_slice(),
        [Field {
            ty: Some(DataType::Enum(enm)),
            ..
        }] if matches!(enm.variants.as_slice(), [(_, variant)] if matches!(variant.fields, Fields::Unit))
    )
}

fn render_field_type(
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    field: &Field,
    ty: &DataType,
    path: &str,
) -> Result<String, Error> {
    let recursive = is_direct_recursive_field(types, ty, path);
    let mut ty = render_datatype(exporter, format, types, ty, path)?;
    if field.optional && !matches!(ty.as_str(), s if s.starts_with("Option<")) {
        ty = format!("Option<{ty}>");
    }
    Ok(if !recursive {
        ty
    } else if let Some(inner) = ty
        .strip_prefix("Option<")
        .and_then(|ty| ty.strip_suffix('>'))
    {
        format!("Option<Box<{inner}>>")
    } else {
        format!("Box<{ty}>")
    })
}

fn is_direct_recursive_field(types: &Types, ty: &DataType, path: &str) -> bool {
    let Some(owner) = types.into_sorted_iter().find(|ndt| {
        path.strip_prefix(&rust_path(ndt))
            .is_some_and(|rest| rest.starts_with('.'))
    }) else {
        return false;
    };
    let owner = rust_path(owner);
    let mut targets = Vec::new();
    collect_direct_targets(types, ty, &mut targets);
    targets.into_iter().any(|target| {
        let target_path = rust_path(target);
        target_path == owner
            || reaches_directly(types, target, &owner, &mut HashSet::from([target_path]))
    })
}

fn reaches_directly(
    types: &Types,
    current: &NamedDataType,
    target: &str,
    visited: &mut HashSet<String>,
) -> bool {
    let Some(ty) = &current.ty else { return false };
    let mut next = Vec::new();
    collect_direct_targets(types, ty, &mut next);
    next.into_iter().any(|ndt| {
        let path = rust_path(ndt);
        path == target || (visited.insert(path) && reaches_directly(types, ndt, target, visited))
    })
}

fn collect_direct_targets<'a>(
    types: &'a Types,
    ty: &'a DataType,
    targets: &mut Vec<&'a NamedDataType>,
) {
    match ty {
        DataType::Reference(Reference::Named(reference)) => {
            if let Some(ndt) = types.get(reference) {
                if ndt.ty.is_none()
                    && let NamedReferenceType::Inline { dt, .. } = &reference.inner
                {
                    collect_direct_targets(types, dt, targets);
                } else {
                    targets.push(ndt);
                }
            } else if let NamedReferenceType::Inline { dt, .. } = &reference.inner {
                collect_direct_targets(types, dt, targets);
            }
        }
        DataType::List(list) if list.length.is_some() => {
            collect_direct_targets(types, &list.ty, targets);
        }
        DataType::Nullable(inner) => collect_direct_targets(types, inner, targets),
        DataType::Tuple(tuple) => {
            for ty in &tuple.elements {
                collect_direct_targets(types, ty, targets);
            }
        }
        DataType::Struct(strct) => collect_direct_field_targets(types, &strct.fields, targets),
        DataType::Enum(enm) => {
            for (_, variant) in &enm.variants {
                collect_direct_field_targets(types, &variant.fields, targets);
            }
        }
        DataType::Intersection(elements) => {
            for ty in elements {
                collect_direct_targets(types, ty, targets);
            }
        }
        DataType::Primitive(_)
        | DataType::List(_)
        | DataType::Map(_)
        | DataType::Generic(_)
        | DataType::Reference(Reference::Opaque(_)) => {}
    }
}

fn collect_direct_field_targets<'a>(
    types: &'a Types,
    fields: &'a Fields,
    targets: &mut Vec<&'a NamedDataType>,
) {
    match fields {
        Fields::Unit => {}
        Fields::Unnamed(fields) => {
            for ty in fields.fields.iter().filter_map(|field| field.ty.as_ref()) {
                collect_direct_targets(types, ty, targets);
            }
        }
        Fields::Named(fields) => {
            for ty in fields
                .fields
                .iter()
                .filter_map(|(_, field)| field.ty.as_ref())
            {
                collect_direct_targets(types, ty, targets);
            }
        }
    }
}

fn render_datatype(
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    ty: &DataType,
    path: &str,
) -> Result<String, Error> {
    debug_assert!(
        format.is_none(),
        "datatypes must be formatted before rendering"
    );
    Ok(match ty {
        DataType::Primitive(Primitive::f16) => {
            return Err(Error::UnsupportedPrimitive {
                path: path.into(),
                primitive: "f16",
            });
        }
        DataType::Primitive(Primitive::f128) => {
            return Err(Error::UnsupportedPrimitive {
                path: path.into(),
                primitive: "f128",
            });
        }
        DataType::Primitive(primitive) => primitive_name(primitive).into(),
        DataType::List(list) => {
            let inner = render_datatype(
                exporter,
                format,
                types,
                &list.ty,
                &format!("{path}.<list_item>"),
            )?;
            match list.length {
                Some(length) => format!("[{inner}; {length}]"),
                None if list.unique => format!("std::collections::HashSet<{inner}>"),
                None => format!("Vec<{inner}>"),
            }
        }
        DataType::Map(map) => format!(
            "std::collections::HashMap<{}, {}>",
            render_datatype(
                exporter,
                format,
                types,
                map.key_ty(),
                &format!("{path}.<map_key>"),
            )?,
            render_datatype(
                exporter,
                format,
                types,
                map.value_ty(),
                &format!("{path}.<map_value>"),
            )?
        ),
        DataType::Tuple(tuple) => match tuple.elements.as_slice() {
            [] => "()".into(),
            [only] => format!(
                "({},)",
                render_datatype(exporter, format, types, only, &format!("{path}.0"))?
            ),
            elements => format!(
                "({})",
                elements
                    .iter()
                    .enumerate()
                    .map(|(index, ty)| {
                        render_datatype(exporter, format, types, ty, &format!("{path}.{index}"))
                    })
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ")
            ),
        },
        DataType::Nullable(inner) => {
            format!(
                "Option<{}>",
                render_datatype(exporter, format, types, inner, path)?
            )
        }
        DataType::Generic(generic) => identifier(generic.name(), path)?,
        DataType::Reference(Reference::Named(reference)) => {
            render_reference(exporter, format, types, reference, path)?
        }
        DataType::Reference(Reference::Opaque(reference)) => {
            if let Some(renderer) = &exporter.opaque_renderer
                && let Some(rendered) = (renderer.0)(reference)
            {
                rendered.into_owned()
            } else {
                return Err(Error::UnsupportedOpaque {
                    path: path.into(),
                    type_name: reference.type_name(),
                });
            }
        }
        DataType::Intersection(_) => {
            return Err(Error::UnsupportedIntersection { path: path.into() });
        }
        DataType::Struct(strct) => match &strct.fields {
            Fields::Unit => "()".into(),
            Fields::Unnamed(fields) => {
                let fields = fields
                    .fields
                    .iter()
                    .filter_map(|field| field.ty.as_ref())
                    .map(|ty| render_datatype(exporter, format, types, ty, path))
                    .collect::<Result<Vec<_>, _>>()?;
                match fields.as_slice() {
                    [only] => format!("({only},)"),
                    _ => format!("({})", fields.join(", ")),
                }
            }
            Fields::Named(_) => {
                return Err(Error::InvalidIdentifier {
                    path: path.into(),
                    name: "anonymous struct type".into(),
                });
            }
        },
        DataType::Enum(enm) if matches!(enm.variants.as_slice(), [(_, variant)] if matches!(variant.fields, Fields::Unit)) => {
            "()".into()
        }
        DataType::Enum(_) => {
            return Err(Error::InvalidIdentifier {
                path: path.into(),
                name: "anonymous enum type".into(),
            });
        }
    })
}

fn render_reference(
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    reference: &NamedReference,
    path: &str,
) -> Result<String, Error> {
    if let NamedReferenceType::Inline { dt, .. } = &reference.inner {
        return render_datatype(exporter, format, types, dt, path);
    }
    if let Some(ndt) = types.get(reference) {
        if ndt.ty.is_none() {
            return Err(Error::DanglingReference {
                path: path.into(),
                reference: format!("{reference:?} (referenced type has no definition)"),
            });
        }
        let mut name = reference_name(exporter, types, ndt, path)?;
        if let NamedReferenceType::Reference { generics, .. } = &reference.inner
            && !generics.is_empty()
        {
            name.push('<');
            name.push_str(
                &generics
                    .iter()
                    .map(|(_, ty)| render_datatype(exporter, format, types, ty, path))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", "),
            );
            name.push('>');
        }
        return Ok(name);
    }

    match &reference.inner {
        NamedReferenceType::Inline { .. } => unreachable!("inline references handled above"),
        NamedReferenceType::Recursive(cycle) => Err(Error::RecursiveInline {
            path: path.into(),
            cycle: format!("{cycle:?}"),
        }),
        NamedReferenceType::Reference { .. } => Err(Error::DanglingReference {
            path: path.into(),
            reference: format!("{reference:?}"),
        }),
    }
}

fn render_generic_definitions(
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
    ndt: &NamedDataType,
) -> Result<String, Error> {
    if ndt.generics.is_empty() {
        return Ok(String::new());
    }
    Ok(format!(
        "<{}>",
        ndt.generics
            .iter()
            .map(|generic| {
                let name = identifier(&generic.name, &rust_path(ndt))?;
                generic
                    .default
                    .as_ref()
                    .map_or(Ok(name.clone()), |default| {
                        render_datatype(exporter, format, types, default, &rust_path(ndt))
                            .map(|default| format!("{name} = {default}"))
                    })
            })
            .collect::<Result<Vec<_>, Error>>()?
            .join(", ")
    ))
}

fn render_derives(out: &mut String, exporter: &Rust, depth: usize) {
    if !exporter.derives.is_empty() {
        line(
            out,
            depth,
            &format!("#[derive({})]", exporter.derives.join(", ")),
        );
    }
}

fn render_name_allow(out: &mut String, depth: usize) {
    line(
        out,
        depth,
        "#[allow(deprecated, non_camel_case_types, non_snake_case)]",
    );
}

fn render_docs(out: &mut String, docs: &str, depth: usize) {
    for doc in docs.lines() {
        let doc = doc.strip_prefix(' ').unwrap_or(doc);
        if doc.is_empty() {
            line(out, depth, "///");
        } else {
            line(out, depth, &format!("/// {doc}"));
        }
    }
}

fn render_deprecated(out: &mut String, deprecated: Option<&Deprecated>, depth: usize) {
    let Some(deprecated) = deprecated else { return };
    let value = match (&deprecated.since, &deprecated.note) {
        (None, None) => "#[deprecated]".into(),
        (None, Some(note)) => format!("#[deprecated = {}]", string_literal(note)),
        (since, note) => {
            let mut args = Vec::new();
            if let Some(since) = since {
                args.push(format!("since = {}", string_literal(since)));
            }
            if let Some(note) = note {
                args.push(format!("note = {}", string_literal(note)));
            }
            format!("#[deprecated({})]", args.join(", "))
        }
    };
    line(out, depth, &value);
}

fn primitive_name(primitive: &Primitive) -> &'static str {
    match primitive {
        Primitive::i8 => "i8",
        Primitive::i16 => "i16",
        Primitive::i32 => "i32",
        Primitive::i64 => "i64",
        Primitive::i128 => "i128",
        Primitive::isize => "isize",
        Primitive::u8 => "u8",
        Primitive::u16 => "u16",
        Primitive::u32 => "u32",
        Primitive::u64 => "u64",
        Primitive::u128 => "u128",
        Primitive::usize => "usize",
        Primitive::f16 => unreachable!("unstable primitive rejected before rendering"),
        Primitive::f32 => "f32",
        Primitive::f64 => "f64",
        Primitive::f128 => unreachable!("unstable primitive rejected before rendering"),
        Primitive::bool => "bool",
        Primitive::char => "char",
        Primitive::str => "String",
    }
}

fn datatype_uses_generic(ty: &DataType, name: &str) -> bool {
    match ty {
        DataType::Generic(generic) => generic.name().as_ref() == name,
        DataType::List(list) => datatype_uses_generic(&list.ty, name),
        DataType::Map(map) => {
            datatype_uses_generic(map.key_ty(), name) || datatype_uses_generic(map.value_ty(), name)
        }
        DataType::Nullable(inner) => datatype_uses_generic(inner, name),
        DataType::Tuple(tuple) => tuple
            .elements
            .iter()
            .any(|ty| datatype_uses_generic(ty, name)),
        DataType::Struct(strct) => fields_use_generic(&strct.fields, name),
        DataType::Enum(enm) => enm
            .variants
            .iter()
            .filter(|(_, variant)| !variant.skip)
            .any(|(_, variant)| fields_use_generic(&variant.fields, name)),
        DataType::Intersection(elements) => {
            elements.iter().any(|ty| datatype_uses_generic(ty, name))
        }
        DataType::Reference(Reference::Named(reference)) => match &reference.inner {
            NamedReferenceType::Inline { dt, .. } => datatype_uses_generic(dt, name),
            NamedReferenceType::Reference { generics, .. } => generics
                .iter()
                .any(|(_, ty)| datatype_uses_generic(ty, name)),
            NamedReferenceType::Recursive(_) => false,
        },
        DataType::Primitive(_) | DataType::Reference(Reference::Opaque(_)) => false,
    }
}

fn fields_use_generic(fields: &Fields, name: &str) -> bool {
    match fields {
        Fields::Unit => false,
        Fields::Unnamed(fields) => fields.fields.iter().any(|field| {
            field
                .ty
                .as_ref()
                .is_some_and(|ty| datatype_uses_generic(ty, name))
        }),
        Fields::Named(fields) => fields.fields.iter().any(|(_, field)| {
            field
                .ty
                .as_ref()
                .is_some_and(|ty| datatype_uses_generic(ty, name))
        }),
    }
}

fn identifier(name: &str, path: &str) -> Result<String, Error> {
    if name.is_empty()
        || name == "_"
        || !name
            .chars()
            .next()
            .is_some_and(|c| c == '_' || unicode_ident::is_xid_start(c))
        || !name
            .chars()
            .all(|c| c == '_' || unicode_ident::is_xid_continue(c))
    {
        return Err(Error::InvalidIdentifier {
            path: path.into(),
            name: name.into(),
        });
    }
    if matches!(name, "self" | "Self" | "super" | "crate") {
        return Err(Error::InvalidIdentifier {
            path: path.into(),
            name: name.into(),
        });
    }
    Ok(if is_keyword(name) {
        format!("r#{name}")
    } else {
        name.into()
    })
}

fn is_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "async"
            | "await"
            | "become"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "final"
            | "fn"
            | "for"
            | "gen"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "override"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "static"
            | "struct"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "union"
            | "unsafe"
            | "unsized"
            | "use"
            | "virtual"
            | "where"
            | "while"
            | "yield"
    )
}

fn exported_name(exporter: &Rust, ndt: &NamedDataType) -> Result<String, Error> {
    if exporter.layout == Layout::ModulePrefixedName {
        let mut segments = module_segments(ndt);
        segments.push(ndt.name.as_ref());
        identifier(&segments.join("_"), &rust_path(ndt))
    } else {
        identifier(&ndt.name, &rust_path(ndt))
    }
}

fn reference_name(
    exporter: &Rust,
    types: &Types,
    ndt: &NamedDataType,
    path: &str,
) -> Result<String, Error> {
    match exporter.layout {
        Layout::FlatFile => exported_name(exporter, ndt),
        Layout::ModulePrefixedName => exported_name(exporter, ndt),
        Layout::Modules | Layout::Namespaces | Layout::Files => {
            let target_segments = module_segments(ndt)
                .into_iter()
                .map(|segment| identifier(segment, &rust_path(ndt)))
                .collect::<Result<Vec<_>, _>>()?;
            let mut segments = owner_module_depth(types, path).map_or_else(
                || vec!["crate".to_string()],
                |depth| {
                    if depth == 0 {
                        vec!["self".to_string()]
                    } else {
                        vec!["super".to_string(); depth]
                    }
                },
            );
            segments.extend(target_segments);
            segments.push(identifier(&ndt.name, &rust_path(ndt))?);
            Ok(segments.join("::"))
        }
    }
}

fn owner_module_depth(types: &Types, path: &str) -> Option<usize> {
    types
        .into_sorted_iter()
        .filter(|ndt| {
            let candidate = rust_path(ndt);
            path == candidate || path.starts_with(&format!("{candidate}."))
        })
        .max_by_key(|ndt| rust_path(ndt).len())
        .map(|ndt| module_segments(ndt).len())
}

fn validate_names(exporter: &Rust, types: &Types) -> Result<(), Error> {
    let mut names = HashMap::new();
    for ndt in types.into_sorted_iter().filter(|ndt| ndt.ty.is_some()) {
        let name = exported_name(exporter, ndt)?;
        let scope = match exporter.layout {
            Layout::FlatFile | Layout::ModulePrefixedName => String::new(),
            Layout::Modules | Layout::Namespaces | Layout::Files => module_segments(ndt).join("::"),
        };
        if let Some(previous) = names.insert((scope, name.clone()), rust_path(ndt)) {
            return Err(Error::DuplicateTypeName {
                name,
                types: (previous, rust_path(ndt)),
            });
        }
    }
    if matches!(
        exporter.layout,
        Layout::Modules | Layout::Namespaces | Layout::Files
    ) {
        validate_module_collisions(exporter, &module_tree(types), "crate")?;
    }
    Ok(())
}

#[derive(Default)]
struct Module<'a> {
    types: Vec<&'a NamedDataType>,
    children: BTreeMap<&'a str, Module<'a>>,
}

fn validate_module_collisions(
    exporter: &Rust,
    module: &Module<'_>,
    path: &str,
) -> Result<(), Error> {
    let type_names = module
        .types
        .iter()
        .map(|ndt| exported_name(exporter, ndt))
        .collect::<Result<HashSet<_>, _>>()?;
    for (child_name, child) in &module.children {
        let child_name = identifier(child_name, path)?;
        if type_names.contains(&child_name) {
            return Err(Error::ModuleTypeCollision {
                path: path.into(),
                name: child_name,
            });
        }
        validate_module_collisions(exporter, child, &format!("{path}::{child_name}"))?;
    }
    Ok(())
}

fn module_tree(types: &Types) -> Module<'_> {
    let mut root = Module::default();
    for ndt in types.into_sorted_iter().filter(|ndt| ndt.ty.is_some()) {
        let mut module = &mut root;
        for segment in module_segments(ndt) {
            module = module.children.entry(segment).or_default();
        }
        module.types.push(ndt);
    }
    root
}

fn render_modules(
    out: &mut String,
    exporter: &Rust,
    format: Option<&dyn Format>,
    types: &Types,
) -> Result<(), Error> {
    fn render(
        out: &mut String,
        exporter: &Rust,
        format: Option<&dyn Format>,
        types: &Types,
        module: &Module<'_>,
        depth: usize,
    ) -> Result<(), Error> {
        for ndt in &module.types {
            render_named(out, exporter, format, types, ndt, depth)?;
        }
        for (name, child) in &module.children {
            let name = identifier(name, name)?;
            render_name_allow(out, depth);
            line(out, depth, &format!("pub mod {name} {{"));
            render(out, exporter, format, types, child, depth + 1)?;
            line(out, depth, "}");
            out.push('\n');
        }
        Ok(())
    }
    render(out, exporter, format, types, &module_tree(types), 0)
}

fn export_files(
    exporter: &Rust,
    root: &Path,
    format: Option<&dyn Format>,
    types: &Types,
) -> Result<(), Error> {
    fn render_module(
        exporter: &Rust,
        root: &Path,
        relative: &Path,
        format: Option<&dyn Format>,
        types: &Types,
        module: &Module<'_>,
        is_root: bool,
        files: &mut HashMap<PathBuf, String>,
    ) -> Result<(), Error> {
        let path = if is_root {
            root.join("mod.rs")
        } else {
            root.join(relative).with_extension("rs")
        };
        let mut out = render_header(exporter);
        for child in module.children.keys() {
            render_name_allow(&mut out, 0);
            line(
                &mut out,
                0,
                &format!("pub mod {};", identifier(child, child)?),
            );
        }
        if !module.children.is_empty() && !module.types.is_empty() {
            out.push('\n');
        }
        for ndt in &module.types {
            render_named(&mut out, exporter, format, types, ndt, 0)?;
        }
        if is_root {
            render_raw(&mut out, exporter);
        }
        files.insert(path, out);
        for (name, child) in &module.children {
            render_module(
                exporter,
                root,
                &relative.join(name),
                format,
                types,
                child,
                false,
                files,
            )?;
        }
        Ok(())
    }

    let mut files = HashMap::new();
    render_module(
        exporter,
        root,
        Path::new(""),
        format,
        types,
        &module_tree(types),
        true,
        &mut files,
    )?;

    std::fs::create_dir_all(root)
        .map_err(|source| Error::io("create output directory", root, source))?;
    remove_stale_generated_files(root, &files)?;
    for (path, source) in files {
        create_parent(&path)?;
        std::fs::write(&path, source)
            .map_err(|source| Error::io("write generated file", &path, source))?;
    }
    Ok(())
}

fn remove_stale_generated_files(
    directory: &Path,
    desired: &HashMap<PathBuf, String>,
) -> Result<bool, Error> {
    let entries = std::fs::read_dir(directory)
        .map_err(|source| Error::io("read output directory", directory, source))?;
    let mut removed_generated = false;
    for entry in entries {
        let entry =
            entry.map_err(|source| Error::io("read output directory", directory, source))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| Error::io("inspect output entry", &path, source))?;
        if file_type.is_symlink() {
            continue;
        }
        if file_type.is_dir() {
            if remove_stale_generated_files(&path, desired)? {
                std::fs::remove_dir(&path)
                    .map_err(|source| Error::io("remove empty output directory", &path, source))?;
                removed_generated = true;
            }
        } else if !desired.contains_key(&path) && path.extension().is_some_and(|ext| ext == "rs") {
            let source = std::fs::read(&path)
                .map_err(|error| Error::io("read generated file", &path, error))?;
            if source.starts_with(GENERATED_MARKER.as_bytes()) {
                std::fs::remove_file(&path)
                    .map_err(|source| Error::io("remove stale generated file", &path, source))?;
                removed_generated = true;
            }
        }
    }
    Ok(removed_generated
        && std::fs::read_dir(directory)
            .map_err(|source| Error::io("read output directory", directory, source))?
            .next()
            .is_none())
}

fn create_parent(path: &Path) -> Result<(), Error> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|source| Error::io("create output directory", parent, source))?;
    }
    Ok(())
}

fn module_segments(ndt: &NamedDataType) -> Vec<&str> {
    ndt.module_path
        .split("::")
        .filter(|segment| !segment.is_empty())
        .collect()
}

fn rust_path(ndt: &NamedDataType) -> String {
    if ndt.module_path.is_empty() {
        ndt.name.to_string()
    } else {
        format!("{}::{}", ndt.module_path, ndt.name)
    }
}

fn line(out: &mut String, depth: usize, value: &str) {
    out.push_str(&"    ".repeat(depth));
    out.push_str(value);
    out.push('\n');
}

fn string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn map_datatype(
    format: Option<&dyn Format>,
    types: &Types,
    ty: &DataType,
    path: &str,
) -> Result<DataType, Error> {
    let Some(format) = format else {
        return Ok(ty.clone());
    };
    let mapped = match format.map_type(types, ty) {
        Ok(Cow::Borrowed(ty)) => ty.clone(),
        Ok(Cow::Owned(ty)) => ty,
        Err(source) if source.to_string().contains("Unresolved generic reference") => ty.clone(),
        Err(source) => return Err(Error::format("datatype formatter failed", path, source)),
    };
    map_datatype_children(Some(format), types, mapped, path)
}

fn map_datatype_children(
    format: Option<&dyn Format>,
    types: &Types,
    mut mapped: DataType,
    path: &str,
) -> Result<DataType, Error> {
    match &mut mapped {
        DataType::List(list) => {
            *list.ty = map_datatype(format, types, &list.ty, &format!("{path}.<list_item>"))?;
        }
        DataType::Map(map) => {
            *map.key_ty_mut() =
                map_datatype(format, types, map.key_ty(), &format!("{path}.<map_key>"))?;
            *map.value_ty_mut() = map_datatype(
                format,
                types,
                map.value_ty(),
                &format!("{path}.<map_value>"),
            )?;
        }
        DataType::Nullable(inner) => **inner = map_datatype(format, types, inner, path)?,
        DataType::Struct(strct) => map_fields(format, types, &mut strct.fields, path)?,
        DataType::Enum(enm) => {
            for (name, variant) in &mut enm.variants {
                map_fields(
                    format,
                    types,
                    &mut variant.fields,
                    &format!("{path}.{name}"),
                )?;
            }
        }
        DataType::Tuple(tuple) => {
            for (index, ty) in tuple.elements.iter_mut().enumerate() {
                *ty = map_datatype(format, types, ty, &format!("{path}.{index}"))?;
            }
        }
        DataType::Intersection(elements) => {
            for ty in elements {
                *ty = map_datatype(format, types, ty, path)?;
            }
        }
        DataType::Reference(Reference::Named(reference)) => match &mut reference.inner {
            NamedReferenceType::Inline { dt, .. } => {
                **dt = map_datatype(format, types, dt, path)?;
            }
            NamedReferenceType::Reference { generics, .. } => {
                for (_, ty) in generics {
                    *ty = map_datatype(format, types, ty, path)?;
                }
            }
            NamedReferenceType::Recursive(_) => {}
        },
        DataType::Primitive(_)
        | DataType::Generic(_)
        | DataType::Reference(Reference::Opaque(_)) => {}
    }
    Ok(mapped)
}

fn map_fields(
    format: Option<&dyn Format>,
    types: &Types,
    fields: &mut Fields,
    path: &str,
) -> Result<(), Error> {
    match fields {
        Fields::Unit => {}
        Fields::Unnamed(fields) => {
            for (index, field) in fields.fields.iter_mut().enumerate() {
                if let Some(ty) = &mut field.ty {
                    *ty = map_datatype(format, types, ty, &format!("{path}.{index}"))?;
                }
            }
        }
        Fields::Named(fields) => {
            for (name, field) in &mut fields.fields {
                if let Some(ty) = &mut field.ty {
                    *ty = map_datatype(format, types, ty, &format!("{path}.{name}"))?;
                }
            }
        }
    }
    Ok(())
}
