use std::time::SystemTime;

use serde::{Deserialize, Serialize};
use specta::{Type, TypeCollection};
use specta_typescript::{BigIntExportBehavior, Typescript};
use tempfile::TempDir;

#[derive(Type)]
struct TypeOne {
    field1: String,
    field2: TypeTwo,
}

#[derive(Type)]
struct TypeTwo {
    my_field: String,
}

#[derive(Type)]
#[specta(collect = false)]
struct NotExported {
    b: i32,
}

#[derive(Type)]
struct ReferingToUnexportedType {
    a: NotExported,
    b: SystemTime,
}

#[derive(Type, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FlattenOnNestedEnum {
    id: String,
    #[serde(flatten)]
    result: NestedEnum,
}

#[derive(Type, Serialize, Deserialize)]
#[serde(tag = "type", content = "value", rename_all = "camelCase")]
enum NestedEnum {
    A(String),
    B(i32),
}

#[test]
fn typescript_export_collection() {
    let types = TypeCollection::default()
        .register::<TypeOne>()
        .register::<TypeTwo>()
        .register::<FlattenOnNestedEnum>()
        .register::<ReferingToUnexportedType>();

    let output = Typescript::default()
        .bigint(BigIntExportBehavior::Number)
        .export(&types)
        .unwrap();

    assert!(output.contains("export type TypeOne"));
    assert!(output.contains("export type TypeTwo"));
    assert!(output.contains("export type FlattenOnNestedEnum"));
    assert!(output.contains("export type NestedEnum"));
    assert!(output.contains("export type ReferingToUnexportedType"));
}

#[test]
fn typescript_export_collection_to_file() {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join("bindings.ts");
    let types = TypeCollection::default()
        .register::<TypeOne>()
        .register::<TypeTwo>()
        .register::<FlattenOnNestedEnum>();

    Typescript::default()
        .bigint(BigIntExportBehavior::Number)
        .export_to(&path, &types)
        .unwrap();

    let output = crate::fs_to_string(&path).unwrap();
    assert!(output.contains("bindings.ts"));
    assert!(output.contains("This file has been generated by Specta"));
    assert!(output.contains("export type TypeOne"));
}
