#![allow(deprecated, non_camel_case_types)]

use std::{borrow::Cow, path::Path, process::Command};

use serde::{Deserialize, Serialize};
use specta::{Format, Type, Types};
use specta_java::{Java, Layout, OptionalStyle};
use tempfile::TempDir;

struct IdentityFormat;

impl Format for IdentityFormat {
    fn map_types(&'_ self, types: &Types) -> Result<Cow<'_, Types>, specta::FormatError> {
        Ok(Cow::Owned(types.clone()))
    }

    fn map_type(
        &'_ self,
        _: &Types,
        datatype: &specta::datatype::DataType,
    ) -> Result<Cow<'_, specta::datatype::DataType>, specta::FormatError> {
        Ok(Cow::Owned(datatype.clone()))
    }
}

/// A documented generic response.
#[derive(Type, Serialize, Deserialize)]
#[specta(collect = false)]
struct Response<T> {
    /// Returned payload.
    value: T,
    optional_count: Option<u32>,
    labels: Vec<String>,
}

#[derive(Type, Serialize, Deserialize)]
#[specta(collect = false)]
#[serde(rename_all = "snake_case")]
enum Status {
    Ready,
    PendingReview,
}

#[derive(Type, Serialize, Deserialize)]
#[specta(collect = false)]
#[serde(tag = "kind", content = "payload")]
enum Event<T> {
    Started,
    Progress(u8),
    Finished { result: T },
}

#[derive(Type, Serialize, Deserialize)]
#[specta(collect = false)]
struct Model {
    response: Response<String>,
    status: Status,
    event: Event<String>,
    lookup: std::collections::HashMap<String, i64>,
    tuple: (String, bool),
}

fn types() -> Types {
    Types::default()
        .register::<Response<String>>()
        .register::<Status>()
        .register::<Event<String>>()
        .register::<Model>()
}

fn temp_dir() -> TempDir {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join(".temp");
    std::fs::create_dir_all(&root).unwrap();
    TempDir::new_in(root).unwrap()
}

fn compile_java(root: &Path, files: &[&Path]) {
    let output = Command::new("javac")
        .arg("--release")
        .arg("17")
        .arg("-d")
        .arg(root.join("classes"))
        .args(files)
        .output()
        .expect("javac must be installed to validate generated Java");
    assert!(
        output.status.success(),
        "generated Java did not compile:\n{}\n{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
        files
            .iter()
            .map(|path| std::fs::read_to_string(path).unwrap())
            .collect::<Vec<_>>()
            .join("\n"),
    );
}

#[test]
fn java_export_raw_and_serde() {
    insta::assert_snapshot!(
        "java-export-raw",
        Java::default().export(&types(), IdentityFormat).unwrap()
    );
    insta::assert_snapshot!(
        "java-export-serde",
        Java::default()
            .export(&types(), specta_serde::Format)
            .unwrap()
    );
    insta::assert_snapshot!(
        "java-export-serde-phases",
        Java::default()
            .export(&types(), specta_serde::PhasesFormat)
            .unwrap()
    );
}

#[test]
fn flat_file_compiles_and_supports_configuration() {
    let temp = temp_dir();
    let path = temp.path().join("ApiTypes.java");
    Java::default()
        .package("dev.specta.generated")
        .class_name("ApiTypes")
        .header("// custom header")
        .with_raw("public static final String VERSION = \"1\";")
        .export_to(&path, &types(), specta_serde::Format)
        .unwrap();

    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.starts_with(
        "// custom header\n// @generated by specta-java (package: dev.specta.generated)\n\npackage"
    ));
    assert!(source.contains("public final class ApiTypes"));
    assert!(source.contains("VERSION"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn files_layout_writes_public_types_that_compile_together() {
    let temp = temp_dir();
    Java::default()
        .package("dev.specta.generated")
        .layout(Layout::Files)
        .export_to(temp.path(), &types(), specta_serde::Format)
        .unwrap();

    let mut files = Vec::new();
    fn collect(path: &Path, files: &mut Vec<std::path::PathBuf>) {
        for entry in std::fs::read_dir(path).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                collect(&path, files);
            } else if path
                .extension()
                .is_some_and(|extension| extension == "java")
            {
                files.push(path);
            }
        }
    }
    collect(temp.path(), &mut files);
    assert_eq!(files.len(), 4);
    let refs = files
        .iter()
        .map(std::path::PathBuf::as_path)
        .collect::<Vec<_>>();
    compile_java(temp.path(), &refs);
}

#[test]
fn files_layout_removes_only_stale_generated_java() {
    let temp = temp_dir();
    let manual = temp.path().join("Manual.java");
    std::fs::write(&manual, "final class Manual {}\n").unwrap();

    let java = Java::default().layout(Layout::Files);
    java.export_to(temp.path(), &types(), IdentityFormat)
        .unwrap();
    java.export_to(temp.path(), &Types::default(), IdentityFormat)
        .unwrap();

    assert!(manual.exists());
    fn count_java(path: &Path) -> usize {
        std::fs::read_dir(path)
            .unwrap()
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .map(|path| {
                if path.is_dir() {
                    count_java(&path)
                } else {
                    usize::from(path.extension().is_some_and(|ext| ext == "java"))
                }
            })
            .sum()
    }
    assert_eq!(
        count_java(temp.path()),
        1,
        "only the manually maintained Java file remains"
    );
}

#[test]
fn files_layout_cleanup_is_scoped_to_the_configured_base_package() {
    let temp = temp_dir();
    let first = Java::default()
        .layout(Layout::Files)
        .package("com.acme.api");
    let second = Java::default()
        .layout(Layout::Files)
        .package("com.acme.admin");

    first
        .export_to(temp.path(), &types(), IdentityFormat)
        .unwrap();
    let first_file = temp
        .path()
        .join("com/acme/api")
        .join(module_path!().replace("::", "/"))
        .join("Model.java");
    assert!(first_file.exists());

    second
        .export_to(temp.path(), &types(), IdentityFormat)
        .unwrap();

    assert!(first_file.exists());
}

#[cfg(unix)]
#[test]
fn files_layout_does_not_follow_directory_symlinks_during_cleanup() {
    use std::os::unix::fs::symlink;

    let output = temp_dir();
    let external = temp_dir();
    let external_generated = external.path().join("External.java");
    std::fs::write(
        &external_generated,
        "// @generated by specta-java\nfinal class External {}\n",
    )
    .unwrap();
    symlink(external.path(), output.path().join("linked")).unwrap();

    Java::default()
        .layout(Layout::Files)
        .export_to(output.path(), &Types::default(), IdentityFormat)
        .unwrap();

    assert!(external_generated.exists());
}

#[test]
fn files_layout_requires_export_to() {
    let error = Java::default()
        .layout(Layout::Files)
        .export(&types(), IdentityFormat)
        .unwrap_err();
    assert!(error.to_string().contains("requires Java::export_to"));
}

#[test]
fn rejects_invalid_packages_and_mismatched_flat_file_names() {
    let package_error = Java::default()
        .package("dev.class")
        .export(&types(), IdentityFormat)
        .unwrap_err();
    assert!(package_error.to_string().contains("Java identifier"));

    let temp = temp_dir();
    let filename_error = Java::default()
        .export_to(temp.path().join("Anything.java"), &types(), IdentityFormat)
        .unwrap_err();
    assert!(filename_error.to_string().contains("Bindings.java"));
}

#[derive(Type, Serialize)]
#[specta(collect = false)]
struct RecordMethodNames {
    clone: String,
    get_class: String,
    #[serde(rename = "hashCode")]
    hash_code: String,
    wait: String,
}

#[test]
fn forbidden_record_component_names_are_escaped_and_compile() {
    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<RecordMethodNames>(),
            specta_serde::Format,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("clone_"));
    assert!(source.contains("hashCode_"));
    assert!(source.contains("wait_"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn module_prefixed_optional_and_inline_apis_are_valid_java() {
    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .layout(Layout::ModulePrefixedName)
        .optionals(OptionalStyle::Optional)
        .export_to(&path, &types(), IdentityFormat)
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("java.util.Optional<java.lang.Long> optional_count"));
    assert!(!source.contains("public record Model("));
    compile_java(temp.path(), &[&path]);

    let inline = Java::default()
        .inline(
            &Types::default(),
            &specta::datatype::DataType::Primitive(specta::datatype::Primitive::i32),
            IdentityFormat,
        )
        .unwrap();
    assert_eq!(inline, "java.lang.Integer");
}

#[test]
fn java_lang_types_cannot_be_shadowed() {
    #[derive(Type)]
    #[specta(collect = false)]
    struct String;

    #[derive(Type)]
    #[specta(collect = false)]
    struct Shadowed {
        value: std::string::String,
        generated: String,
    }

    #[derive(Type, Serialize)]
    #[specta(collect = false)]
    #[serde(tag = "kind")]
    enum ShadowEvent {
        Started { count: u8 },
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default()
                .register::<String>()
                .register::<Shadowed>()
                .register::<ShadowEvent>(),
            specta_serde::Format,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("java.lang.String value"));
    assert!(source.contains("String generated"));
    assert!(source.contains("java.lang.String kind"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn enum_type_name_collisions_match_java_rules() {
    #[derive(Type)]
    #[specta(collect = false)]
    enum UnitFoo {
        UnitFoo,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    enum DataFoo {
        DataFoo(u8),
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<UnitFoo>(),
            IdentityFormat,
        )
        .unwrap();
    compile_java(temp.path(), &[&path]);

    assert!(
        Java::default()
            .export(&Types::default().register::<DataFoo>(), IdentityFormat)
            .unwrap_err()
            .to_string()
            .contains("duplicate Java type name")
    );
}

#[test]
fn field_suffixes_skip_existing_normalized_names() {
    #[derive(Type, Serialize)]
    #[specta(collect = false)]
    struct SuffixedFields {
        foo: u8,
        foo_2: u8,
        #[serde(rename = "foo-")]
        foo_dash: u8,
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<SuffixedFields>(),
            specta_serde::Format,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("java.lang.Short foo_3"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn empty_generic_enums_return_an_export_error() {
    let mut types = Types::default();
    specta::datatype::NamedDataType::new("EmptyGeneric", &mut types, |_, datatype| {
        datatype.generics = vec![specta::datatype::GenericDefinition::new("T".into(), None)].into();
        datatype.ty = Some(specta::datatype::Enum::default().into());
    });

    let error = Java::default().export(&types, IdentityFormat).unwrap_err();
    assert!(error.to_string().contains("at least one non-skipped"));
}

#[test]
fn string_enum_backing_fields_do_not_collide_with_constants() {
    #[derive(Type, Serialize)]
    #[specta(collect = false)]
    enum ValueEnum {
        #[serde(rename = "value")]
        Value,
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<ValueEnum>(),
            specta_serde::Format,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("private final java.lang.String value_"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn files_layout_rejects_default_package_references_from_named_packages() {
    let mut types = Types::default();
    let root = specta::datatype::NamedDataType::new("Root", &mut types, |_, datatype| {
        datatype.module_path = "".into();
        datatype.ty = Some(specta::datatype::Struct::unit().into());
    });
    specta::datatype::NamedDataType::new("Nested", &mut types, |_, datatype| {
        datatype.module_path = "nested".into();
        datatype.ty = Some(
            specta::datatype::Struct::named()
                .field(
                    "root",
                    specta::datatype::Field::new(root.reference(Vec::new()).into()),
                )
                .build(),
        );
    });

    let error = Java::default()
        .layout(Layout::Files)
        .export_to(temp_dir().path(), &types, IdentityFormat)
        .unwrap_err();
    assert!(error.to_string().contains("configure a base package"));
}

#[test]
fn genuine_inline_single_variant_enums_remain_enums() {
    #[derive(Type)]
    #[specta(collect = false)]
    enum SingleVariant {
        Only,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    struct InlineSingleVariant {
        #[specta(inline)]
        status: SingleVariant,
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<InlineSingleVariant>(),
            IdentityFormat,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("public enum Status"));
    assert!(source.contains("Status status"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn equal_nested_names_are_allowed_in_separate_scopes() {
    #[derive(Type)]
    #[specta(collect = false)]
    struct Inner {
        value: u8,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    struct A {
        #[specta(inline)]
        inner: Inner,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    struct B {
        #[specta(inline)]
        inner: Inner,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    struct Outer {
        #[specta(inline)]
        a: A,
        #[specta(inline)]
        b: B,
    }

    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(&path, &Types::default().register::<Outer>(), IdentityFormat)
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("public record A"));
    assert!(source.contains("public record B"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn rejects_wrapper_and_nested_declaration_collisions() {
    #[derive(Type)]
    #[specta(collect = false)]
    struct Bindings;

    #[derive(Type)]
    #[specta(collect = false)]
    struct Inner {
        value: String,
    }

    #[derive(Type)]
    #[specta(collect = false)]
    #[allow(non_snake_case)]
    struct NestedCollision {
        #[specta(inline)]
        foo_bar: Inner,
        #[specta(inline)]
        fooBar: Inner,
    }

    assert!(
        Java::default()
            .export(&Types::default().register::<Bindings>(), IdentityFormat)
            .unwrap_err()
            .to_string()
            .contains("duplicate Java type name")
    );
    assert!(
        Java::default()
            .export(
                &Types::default().register::<NestedCollision>(),
                IdentityFormat,
            )
            .unwrap_err()
            .to_string()
            .contains("duplicate Java type name")
    );
}

#[allow(non_camel_case_types)]
#[derive(Type)]
#[specta(collect = false)]
struct UnderscoreGeneric<T_Value> {
    value: T_Value,
}

#[test]
fn normalized_generic_names_are_used_consistently() {
    let temp = temp_dir();
    let path = temp.path().join("Bindings.java");
    Java::default()
        .export_to(
            &path,
            &Types::default().register::<UnderscoreGeneric<String>>(),
            IdentityFormat,
        )
        .unwrap();
    let source = std::fs::read_to_string(&path).unwrap();
    assert!(source.contains("UnderscoreGeneric<TValue>"));
    assert!(source.contains("TValue value"));
    compile_java(temp.path(), &[&path]);
}

#[test]
fn non_java_identifiers_are_safely_escaped() {
    #[derive(Type, Serialize)]
    #[specta(collect = false)]
    #[serde(rename = "invalid/name")]
    struct Invalid;

    let source = Java::default()
        .export(
            &Types::default().register::<Invalid>(),
            specta_serde::Format,
        )
        .unwrap();
    assert!(source.contains("record InvalidName"));
}
