[package]
name = "specta-examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
specta = { path = "../specta", features = ["derive", "export"] }
specta-typescript = { path = "../specta-typescript" }

[lints]
workspace = true
