use std::{borrow::Cow, collections::BTreeSet, fmt, path::Path};

use specta::{Format, Types};

use crate::{Error, render};

/// Controls whether generated declarations use `kotlinx.serialization`.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Serialization {
    /// Add standard `@Serializable` and `@SerialName` annotations.
    ///
    /// Shapes whose standard Kotlinx encoding would differ from Serde are rejected.
    Kotlinx,
    /// Generate plain Kotlin declarations without serialization annotations.
    #[default]
    None,
}

/// Policy for exporter-specific opaque references that Kotlin does not recognize.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum UnknownType {
    /// Return a contextual exporter error.
    #[default]
    Error,
    /// Approximate the value as nullable Kotlin `Any`.
    Any,
}

/// Controls the output layout.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Layout {
    /// Put every declaration in one Kotlin source file.
    #[default]
    FlatFile,
    /// Prefix declaration names with their Rust module path in one source file.
    ModulePrefixedName,
    /// Write one `.kt` file per named type.
    Files,
}

/// Indentation used for generated declarations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndentStyle {
    /// Indent with the requested number of spaces.
    Spaces(usize),
    /// Indent with tabs.
    Tabs,
}

impl Default for IndentStyle {
    fn default() -> Self {
        Self::Spaces(4)
    }
}

/// Naming conversion applied to declarations and properties.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum NamingConvention {
    /// Keep names provided by Specta and the active formatter.
    #[default]
    Preserve,
    /// Convert names to PascalCase.
    PascalCase,
    /// Convert names to camelCase.
    CamelCase,
    /// Convert names to snake_case.
    SnakeCase,
}

/// Kotlin language exporter.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct Kotlin {
    /// Content prepended to every generated file.
    pub header: Cow<'static, str>,
    /// Kotlin package for generated declarations.
    pub package: Option<Cow<'static, str>>,
    /// Output layout.
    pub layout: Layout,
    /// Indentation style.
    pub indent: IndentStyle,
    /// Identifier naming convention.
    pub naming: NamingConvention,
    /// Serialization integration.
    pub serialization: Serialization,
    /// Whether generated constructor properties use `var` instead of `val`.
    pub mutable_properties: bool,
    /// Policy for unknown exporter-specific opaque types.
    pub unknown_types: UnknownType,
    raw: Vec<Cow<'static, str>>,
}

impl Default for Kotlin {
    fn default() -> Self {
        Self {
            header: Cow::Borrowed(
                "// This file has been generated by Specta. Do not edit it manually.",
            ),
            package: None,
            layout: Layout::FlatFile,
            indent: IndentStyle::default(),
            naming: NamingConvention::default(),
            serialization: Serialization::None,
            mutable_properties: false,
            unknown_types: UnknownType::Error,
            raw: Vec::new(),
        }
    }
}

impl Kotlin {
    /// Creates an exporter with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets content prepended to generated files.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Sets the Kotlin package for generated declarations.
    pub fn package(mut self, package: impl Into<Cow<'static, str>>) -> Self {
        self.package = Some(package.into());
        self
    }

    /// Removes the package declaration.
    pub fn without_package(mut self) -> Self {
        self.package = None;
        self
    }

    /// Sets the output layout.
    pub fn layout(mut self, layout: Layout) -> Self {
        self.layout = layout;
        self
    }

    /// Sets indentation.
    pub fn indent(mut self, indent: IndentStyle) -> Self {
        self.indent = indent;
        self
    }

    /// Sets identifier naming conversion.
    pub fn naming(mut self, naming: NamingConvention) -> Self {
        self.naming = naming;
        self
    }

    /// Enables or disables serialization annotations.
    pub fn serialization(mut self, serialization: Serialization) -> Self {
        self.serialization = serialization;
        self
    }

    /// Controls whether constructor properties are mutable.
    pub fn mutable_properties(mut self, mutable: bool) -> Self {
        self.mutable_properties = mutable;
        self
    }

    /// Configures how unknown exporter-specific opaque references are rendered.
    pub fn unknown_types(mut self, policy: UnknownType) -> Self {
        self.unknown_types = policy;
        self
    }

    /// Appends raw Kotlin source after generated declarations.
    pub fn with_raw(mut self, source: impl Into<Cow<'static, str>>) -> Self {
        self.raw.push(source.into());
        self
    }

    /// Exports all types into a single string.
    pub fn export(&self, types: &Types, format: impl Format) -> Result<String, Error> {
        if self.layout == Layout::Files {
            return Err(Error::ExportRequiresExportTo(self.layout));
        }
        let types = format_types(types, &format)?;
        render::render_file(self, types.as_ref(), Some(&format), render::Selection::All)
    }

    /// Exports types to a file, or to a directory for [`Layout::Files`].
    pub fn export_to(
        &self,
        path: impl AsRef<Path>,
        types: &Types,
        format: impl Format,
    ) -> Result<(), Error> {
        let path = path.as_ref();
        let types = format_types(types, &format)?;
        let types = types.as_ref();

        if self.layout != Layout::Files {
            let source = render::render_file(self, types, Some(&format), render::Selection::All)?;
            if let Some(parent) = path
                .parent()
                .filter(|parent| !parent.as_os_str().is_empty())
            {
                std::fs::create_dir_all(parent).map_err(|source| Error::CreateDir {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
            return std::fs::write(path, source).map_err(|source| Error::WriteFile {
                path: path.to_path_buf(),
                source,
            });
        }

        std::fs::create_dir_all(path).map_err(|source| Error::CreateDir {
            path: path.to_path_buf(),
            source,
        })?;
        let mut filenames = BTreeSet::new();
        let mut casefolded_filenames = BTreeSet::new();
        let mut files = Vec::new();
        for ndt in types.into_sorted_iter().filter(|ndt| ndt.ty.is_some()) {
            let filename = format!("{}.kt", render::filename(self, &ndt.name)?);
            if !filenames.insert(filename.clone())
                || !casefolded_filenames.insert(filename.to_lowercase())
            {
                return Err(Error::DuplicateTypeName { name: filename });
            }
            let source =
                render::render_file(self, types, Some(&format), render::Selection::One(ndt))?;
            files.push((filename, source));
        }

        if !self.raw.is_empty() {
            if filenames.contains("Specta.kt") || !casefolded_filenames.insert("specta.kt".into()) {
                return Err(Error::DuplicateTypeName {
                    name: "Specta.kt".into(),
                });
            }
            let source =
                render::render_file(self, types, Some(&format), render::Selection::RawOnly)?;
            filenames.insert("Specta.kt".into());
            files.push(("Specta.kt".into(), source));
        }

        let manifest = path.join(".specta-kotlin-files");
        match std::fs::read_to_string(&manifest) {
            Ok(previous) => {
                for filename in previous.lines().filter(|name| !filenames.contains(*name)) {
                    let stale = Path::new(filename);
                    if stale
                        .file_name()
                        .is_none_or(|name| name != stale.as_os_str())
                        || stale.extension().is_none_or(|extension| extension != "kt")
                    {
                        continue;
                    }
                    let stale = path.join(stale);
                    match std::fs::remove_file(&stale) {
                        Ok(()) => {}
                        Err(source) if source.kind() == std::io::ErrorKind::NotFound => {}
                        Err(source) => {
                            return Err(Error::RemoveFile {
                                path: stale,
                                source,
                            });
                        }
                    }
                }
            }
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::ReadFile {
                    path: manifest,
                    source,
                });
            }
        }

        for (filename, source) in files {
            let file = path.join(filename);
            std::fs::write(&file, source)
                .map_err(|source| Error::WriteFile { path: file, source })?;
        }
        let contents = filenames.into_iter().collect::<Vec<_>>().join("\n") + "\n";
        std::fs::write(&manifest, contents).map_err(|source| Error::WriteFile {
            path: manifest,
            source,
        })?;
        Ok(())
    }

    pub(crate) fn raw(&self) -> &[Cow<'static, str>] {
        &self.raw
    }

    pub(crate) fn indentation(&self, depth: usize) -> String {
        match self.indent {
            IndentStyle::Spaces(count) => " ".repeat(count * depth),
            IndentStyle::Tabs => "\t".repeat(depth),
        }
    }
}

fn format_types<'a>(types: &'a Types, format: &'a dyn Format) -> Result<Cow<'a, Types>, Error> {
    format
        .map_types(types)
        .map_err(|source| Error::format("type graph formatter failed", source))
}

impl fmt::Display for Layout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}
