// This file has been generated by Specta. DO NOT EDIT.
import Foundation

/// A comprehensive example demonstrating multi-line comment support
/// 
/// This example shows how Specta Swift handles complex documentation
/// including:
/// - Multi-line type documentation
/// - Bullet points and formatting
/// - Complex technical descriptions
/// 
/// The generated Swift code will have properly formatted doc comments
/// that are compatible with Swift's documentation system.
enum ApiResponse<T>: Codable {
    case success(data: T, status: UInt16, headers: [(String, String)]?)
    case error(message: String, code: UInt32, details: String?)
    case loading(progress: Float, estimatedTime: UInt64?)
}

/// A user account in the system
/// 
/// This struct represents a complete user account with all necessary
/// information for authentication, authorization, and personalization.
/// 
/// # Security Notes
/// - The `password_hash` field should never be logged or exposed
/// - The `api_key` is sensitive and should be treated as a secret
/// - All timestamps are in UTC
struct User: Codable {
    let id: UInt32
    let username: String
    let email: String
    let isActive: Bool
    let createdAt: String
    let lastLogin: String?
}

