// Generated by MyApp - Custom Header
import Foundation

enum api_result<T>: Codable {
    case success(data: T, status: UInt16)
    case error(message: String, code: UInt32)
    case loading(progress: Float)
}

struct user: Codable {
    let id: UInt32
    let name: String
    let email: Optional<String>
    let role: user_role
}

enum user_role: Codable {
    case guest
    case user(permissions: [String])
    case admin(level: UInt8, department: String)
    case super_admin(access_level: UInt32)
}

