use std::{borrow::Cow, path::Path};

use specta::{Format as FormatTrait, Types};

use crate::{
    error::{Error, Result},
    primitives::export_type,
    toposort::topological_sort,
};

/// ReScript language exporter.
#[derive(Debug, Clone)]
pub struct ReScript {
    /// Header comment placed at the top of the generated file.
    pub header: Cow<'static, str>,
    /// Whether to apply serde transformations. `true` by default.
    pub serde: bool,
}

impl Default for ReScript {
    fn default() -> Self {
        Self {
            header: "// This file has been generated by Specta. DO NOT EDIT.".into(),
            serde: false,
        }
    }
}

impl ReScript {
    /// Create a new ReScript exporter with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the header comment for the generated file.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Enable Serde transformation.
    pub fn with_serde(mut self) -> Self {
        self.serde = true;
        self
    }

    /// Disable Serde transformation.
    pub fn without_serde(mut self) -> Self {
        self.serde = false;
        self
    }

    /// Export all types in the collection to a ReScript string.
    pub fn export(&self, types: &Types) -> Result<String> {
        let processed: Cow<Types> = if self.serde {
            specta_serde::Format
                .map_types(types)
                .map_err(|e| Error::format("serde apply failed", e))?
        } else {
            Cow::Borrowed(types)
        };

        let mut out = String::new();

        if !self.header.is_empty() {
            out.push_str(&self.header);
            out.push('\n');
        }

        for ndt in topological_sort(processed.as_ref())? {
            let rendered = export_type(&processed, ndt)?;
            if !rendered.is_empty() {
                out.push('\n');
                out.push_str(&rendered);
            }
        }

        Ok(out)
    }

    /// Export all types to a `.res` file.
    pub fn export_to(&self, path: impl AsRef<Path>, types: &Types) -> Result<()> {
        let content = self.export(types)?;
        if let Some(parent) = path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
        Ok(())
    }
}

