use std::{borrow::Cow, collections::HashMap, path::Path};

use specta::{
    Format as FormatTrait, Types,
    datatype::{DataType, Fields, NamedReferenceType, Reference},
};

use crate::{
    error::{Error, Result},
    primitives::{export_type, is_rescript_builtin_type, is_valid_type_name, type_name},
    toposort::topological_sort,
};

/// ReScript language exporter.
#[derive(Debug, Clone)]
pub struct ReScript {
    /// Header comment placed at the top of the generated file.
    pub header: Cow<'static, str>,
    /// Whether to apply serde transformations. `true` by default.
    pub serde: bool,
}

impl Default for ReScript {
    fn default() -> Self {
        Self {
            header: "// This file has been generated by Specta. DO NOT EDIT.".into(),
            serde: false,
        }
    }
}

impl ReScript {
    /// Create a new ReScript exporter with default configuration.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the header comment for the generated file.
    pub fn header(mut self, header: impl Into<Cow<'static, str>>) -> Self {
        self.header = header.into();
        self
    }

    /// Enable Serde transformation.
    pub fn with_serde(mut self) -> Self {
        self.serde = true;
        self
    }

    /// Disable Serde transformation.
    pub fn without_serde(mut self) -> Self {
        self.serde = false;
        self
    }

    /// Export all types in the collection to a ReScript string.
    pub fn export(&self, types: &Types) -> Result<String> {
        if self.serde {
            validate_serde_enum_representations(types)?;
        }
        let processed: Cow<Types> = if self.serde {
            let processed = specta_serde::Format
                .map_types(types)
                .map_err(|e| Error::format("serde apply failed", e))?;
            preserve_standard_result(types, processed)
        } else {
            Cow::Borrowed(types)
        };

        validate_type_names(&processed)?;

        let mut out = String::new();

        if !self.header.is_empty() {
            out.push_str(&self.header);
            out.push('\n');
        }

        for group in topological_sort(processed.as_ref()) {
            let recursive = group.len() > 1
                || group.iter().any(|ty| {
                    ty.ty
                        .as_ref()
                        .is_some_and(|dt| crate::toposort::is_self_recursive(dt, &processed, ty))
                });
            if recursive
                && group.iter().any(|ty| {
                    matches!(
                        &ty.ty,
                        Some(DataType::Struct(structure))
                            if matches!(structure.fields, Fields::Unnamed(_))
                    )
                })
            {
                return Err(Error::UnsupportedType(
                    "Recursive unnamed structs cannot be represented as ReScript type aliases"
                        .to_string(),
                ));
            }
            let mut first_declaration = true;
            for ndt in group {
                let mut rendered = export_type(&processed, ndt)?;
                if recursive {
                    rendered = rendered
                        .split_inclusive('\n')
                        .map(|line| {
                            let Some(declaration) = line.strip_prefix("type ") else {
                                return line.to_string();
                            };
                            let keyword = if std::mem::take(&mut first_declaration) {
                                "type rec "
                            } else {
                                "and "
                            };
                            format!("{keyword}{declaration}")
                        })
                        .collect();
                }
                if !rendered.is_empty() {
                    out.push('\n');
                    out.push_str(&rendered);
                }
            }
        }

        Ok(out)
    }

    /// Export all types to a `.res` file.
    pub fn export_to(&self, path: impl AsRef<Path>, types: &Types) -> Result<()> {
        let content = self.export(types)?;
        if let Some(parent) = path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
        Ok(())
    }
}

fn validate_serde_enum_representations(types: &Types) -> Result<()> {
    types
        .into_unsorted_iter()
        .filter(|ty| !(ty.name == "Result" && ty.module_path == "std::result"))
        .filter_map(|ty| ty.ty.as_ref())
        .try_for_each(validate_serde_datatype)
}

fn validate_serde_datatype(dt: &DataType) -> Result<()> {
    match dt {
        DataType::Primitive(_) | DataType::Generic(_) => Ok(()),
        DataType::Nullable(inner) => validate_serde_datatype(inner),
        DataType::List(list) => validate_serde_datatype(&list.ty),
        DataType::Map(map) => {
            validate_serde_datatype(map.key_ty())?;
            validate_serde_datatype(map.value_ty())
        }
        DataType::Struct(structure) => validate_serde_fields(&structure.fields),
        DataType::Enum(enumeration) => {
            let untagged = enumeration
                .attributes
                .get_named_as::<bool>("serde:container:untagged")
                == Some(&true);
            if untagged {
                return Err(Error::UnsupportedType(
                    "Serde untagged enums cannot be represented as ReScript variants".to_string(),
                ));
            }
            if enumeration.attributes.contains_key("serde:container:tag") {
                return Err(Error::UnsupportedType(
                    "Serde internally and adjacently tagged enums cannot be represented as ReScript variants"
                        .to_string(),
                ));
            }
            Err(Error::UnsupportedType(
                "Serde externally tagged enums cannot be represented as ReScript variants"
                    .to_string(),
            ))
        }
        DataType::Tuple(tuple) => tuple.elements.iter().try_for_each(validate_serde_datatype),
        DataType::Intersection(types) => types.iter().try_for_each(validate_serde_datatype),
        DataType::Reference(Reference::Named(named)) => match &named.inner {
            NamedReferenceType::Inline { dt, .. } => validate_serde_datatype(dt),
            NamedReferenceType::Reference { generics, .. } => generics
                .iter()
                .try_for_each(|(_, ty)| validate_serde_datatype(ty)),
            NamedReferenceType::Recursive(recursive) => recursive
                .generics()
                .iter()
                .try_for_each(|(_, ty)| validate_serde_datatype(ty)),
        },
        DataType::Reference(Reference::Opaque(_)) => Ok(()),
    }
}

fn validate_serde_fields(fields: &Fields) -> Result<()> {
    match fields {
        Fields::Unit => Ok(()),
        Fields::Unnamed(fields) => fields
            .fields
            .iter()
            .filter_map(|field| field.ty.as_ref())
            .try_for_each(validate_serde_datatype),
        Fields::Named(fields) => fields
            .fields
            .iter()
            .filter_map(|(_, field)| field.ty.as_ref())
            .try_for_each(validate_serde_datatype),
    }
}

fn preserve_standard_result<'a>(original: &Types, processed: Cow<'a, Types>) -> Cow<'a, Types> {
    let Some(result) = original
        .into_unsorted_iter()
        .find(|ty| ty.name == "Result" && ty.module_path == "std::result")
        .cloned()
    else {
        return processed;
    };

    Cow::Owned(processed.into_owned().map(|ty| {
        if ty.name == result.name && ty.module_path == result.module_path {
            result.clone()
        } else {
            ty
        }
    }))
}

fn validate_type_names(types: &Types) -> Result<()> {
    let mut names = HashMap::<String, String>::new();
    for ty in types.into_sorted_iter().filter(|ty| ty.ty.is_some()) {
        let name = type_name(&ty.name);
        let standard_result = ty.name == "Result" && ty.module_path == "std::result";
        if !is_valid_type_name(&name) || (is_rescript_builtin_type(&name) && !standard_result) {
            return Err(Error::InvalidTypeName(name));
        }

        if standard_result {
            continue;
        }

        let owner = format!("{}::{}", ty.module_path, ty.name);
        insert_type_name(&mut names, name.clone(), owner.clone())?;

        let Some(DataType::Enum(enumeration)) = &ty.ty else {
            continue;
        };
        for (variant_name, variant) in &enumeration.variants {
            let Fields::Named(fields) = &variant.fields else {
                continue;
            };
            if variant.skip || !fields.fields.iter().any(|(_, field)| field.ty.is_some()) {
                continue;
            }

            insert_type_name(
                &mut names,
                format!("{name}{variant_name}Fields"),
                format!("{owner}::{variant_name} (generated record)"),
            )?;
        }
    }
    Ok(())
}

fn insert_type_name(
    names: &mut HashMap<String, String>,
    name: String,
    owner: String,
) -> Result<()> {
    if let Some(first) = names.insert(name.clone(), owner.clone()) {
        return Err(Error::DuplicateTypeName {
            name,
            first,
            second: owner,
        });
    }
    Ok(())
}
