//! TODO

use std::{borrow::Cow, fmt, sync::Arc};

use specta::{
    Type, Types,
    datatype::{DataType, Fields, NamedReferenceType, Primitive, Reference},
};

mod rules;

/// A transformer. Defines both a type and a runtime transformer.
#[derive(Clone)]
#[non_exhaustive]
pub struct Transform {
    /// The type transformation function
    ///
    /// This must match up with the type produced by the runtime.
    data_type: Arc<dyn Fn(DataType) -> DataType + Send + Sync>,
    /// The runtime transform function
    ///
    /// This is called with the argument being a Typescript identifier.
    /// It should output some transformation on the identifier.
    /// Eg. `|i| format!("new Date({i})")` could be one valid implementation.
    runtime: Option<Arc<dyn Fn(&str) -> String + Send + Sync>>,
}

impl fmt::Debug for Transform {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Transform")
            .field("typ", &format!("{:p}", self.data_type))
            .field(
                "runtime",
                &match &self.runtime {
                    Some(r) => format!("{r:p}"),
                    None => "<none>".into(),
                },
            )
            .finish()
    }
}

impl Transform {
    pub fn new(
        dt: impl Fn(DataType) -> DataType + Send + Sync + 'static,
        runtime: impl Fn(&str) -> String + Send + Sync + 'static,
    ) -> Self {
        Self {
            data_type: Arc::new(dt),
            runtime: Some(Arc::new(runtime)),
        }
    }

    pub fn new_identity_runtime(dt: impl Fn(DataType) -> DataType + Send + Sync + 'static) -> Self {
        Self {
            data_type: Arc::new(dt),
            runtime: None,
        }
    }
}

/// A rule for a specific named data type.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub(crate) struct Rule {
    /// NDT's name
    pub(crate) name: Cow<'static, str>,
    /// NDT's module path
    pub(crate) module_path: Cow<'static, str>,
    /// The type transformation for serializing.
    /// This is JS -> Rust
    pub(crate) serialize: Transform,
    /// The type transformation for deserializing.
    /// This is Rust -> JS
    pub(crate) deserialize: Transform,
}

/// TODO
#[derive(Debug, Clone)]
pub struct RichTypesConfiguration {
    rules: Vec<Rule>,
    remapper: Option<specta_util::Remapper>,
    lossless_bigint: bool,
    lossless_floats: bool,
}

impl RichTypesConfiguration {
    /// Construct a [`RichTypesConfiguration`] without the default rules.
    ///
    /// You should prefer [`RichTypesConfiguration::default`] when possible as the default rules are likely to be more suitable for your use case.
    pub fn empty() -> Self {
        Self {
            rules: Default::default(),
            remapper: None,
            lossless_bigint: false,
            lossless_floats: false,
        }
    }

    /// Define a new rule for a given type `T`.
    ///
    /// Note: this will only worked if applied to a named type like generated by the `Type` macro. It will not work with primitives.
    ///
    pub fn define<T: Type>(&mut self, serialize: Transform, deserialize: Transform) -> &mut Self {
        let mut types = Types::default();
        let ndt = match T::definition(&mut types) {
            DataType::Reference(Reference::Named(r)) => types.get(&r),
            _ => None,
        };
        if let Some(ndt) = ndt {
            self.rules.push(Rule {
                name: ndt.name.clone(),
                module_path: ndt.module_path.clone(),
                serialize,
                deserialize,
            });
        }

        self
    }

    /// Enable lossless support for large number types (BigInt's).
    ///
    /// This assumes your runtime is configured to handle losslessly transmitting the `BigInt`'s.
    /// Refer to [specta-rs/specta#203](https://github.com/specta-rs/specta/issues/203) for the implementation details around this.
    pub fn enable_lossless_bigints(&mut self) -> &mut Self {
        if !self.lossless_bigint {
            self.lossless_bigint = true;

            for primitive in [
                Primitive::usize,
                Primitive::isize,
                Primitive::u64,
                Primitive::i64,
                Primitive::u128,
                Primitive::i128,
            ] {
                // TODO: For input it should be `bigint | number` when phased is enabled??? How do we know that???

                self.remapper = Some(self.remapper.take().unwrap_or_default().rule(
                    DataType::Primitive(primitive),
                    Reference::opaque(crate::opaque::BigInt).into(),
                ));
            }
        }

        self
    }

    /// Enable lossless float support.
    ///
    /// By enabling this your asserting your runtime *MUST* preserve `NaN`, `Infinity` and `-Infinity` values from JS to Rust. This constrain is REQUIRED for this to not have runtime issues.
    ///
    /// Refer to [specta-rs/specta#203](https://github.com/specta-rs/specta/issues/203) for the implementation details around this.
    pub fn enable_lossless_floats(&mut self) -> &mut Self {
        if !self.lossless_floats {
            self.lossless_floats = true;

            // We don't map `f128` as it just can't exist in JS.
            for primitive in [Primitive::f16, Primitive::f32, Primitive::f64] {
                // This remaps `number | null` to `number`, which is correct if the runtime can handle it.
                self.remapper = Some(self.remapper.take().unwrap_or_default().rule(
                    DataType::Primitive(primitive),
                    Reference::opaque(crate::opaque::Number).into(),
                ));
            }
        }

        self
    }

    /// Transform a [`Types`] collection using the configured rules.
    ///
    /// This will ensure all of your types match the values match what the JS transform will output.
    pub fn apply_types<'a>(&self, types: &'a Types) -> Cow<'a, Types> {
        let mut types = Cow::Borrowed(types);

        if let Some(remapper) = self.remapper.as_ref() {
            types = Cow::Owned(remapper.remap_types(types.into_owned()));
        }

        if !self.rules.is_empty() {
            types = Cow::Owned(types.into_owned().map(|mut ndt| {
                if let Some(rule) = self
                    .rules
                    .iter()
                    .find(|r| r.name == ndt.name && r.module_path == ndt.module_path)
                    && let Some(dt) = ndt.ty.take()
                {
                    ndt.ty = Some((rule.typ)(dt));
                }

                ndt
            }));
        }

        types
    }

    /// Scan a [`DataType`] tree applying all rules and building a JS runtime transform, and an updated type.
    ///
    /// This assumes [`RichTypesConfiguration::apply_types`] has already been applied to the [`Types`].
    /// Therefore the type updates will be shallow (up until references to the `Types`).
    ///
    /// The JavaScript transform will be deeply nested and will be applied around the JS identifier which is provided.
    ///
    /// If no rules are matched, `None` is returned, if the type doesn't require transformations, `Some((None, runtime_str))` is returned.
    ///
    pub fn apply(
        &self,
        types: &Types,
        dt: &DataType,
        js_ident: &str,
    ) -> Option<(Option<DataType>, String)> {
        self.apply_inner(types, dt, js_ident, &mut Vec::new())
    }

    fn apply_inner(
        &self,
        types: &Types,
        dt: &DataType,
        js_ident: &str,
        stack: &mut Vec<(Cow<'static, str>, Cow<'static, str>)>,
    ) -> Option<(Option<DataType>, String)> {
        let result = match dt {
            DataType::Reference(Reference::Named(r)) => match &r.inner {
                NamedReferenceType::Inline { dt, .. } => {
                    self.apply_inner(types, dt, js_ident, stack)
                }
                NamedReferenceType::Recursive => None,
                NamedReferenceType::Reference { .. } => {
                    let ndt = types.get(r)?;
                    let rule = self
                        .rules
                        .iter()
                        .find(|r| r.name == ndt.name && r.module_path == ndt.module_path);

                    if let Some(rule) = rule {
                        return Some((
                            ndt.ty.clone().map(|dt| (rule.typ)(dt)),
                            (rule.serialize_runtime)(js_ident),
                        ));
                    }

                    let ty = ndt.ty.as_ref()?;
                    let key = (ndt.name.clone(), ndt.module_path.clone());
                    if stack.contains(&key) {
                        return None;
                    }
                    stack.push(key);
                    let result = self
                        .apply_inner(types, ty, js_ident, stack)
                        .map(|(_, runtime)| (None, runtime));
                    stack.pop();
                    result
                }
            },
            DataType::Struct(s) => match &s.fields {
                Fields::Named(fields) => {
                    let mut ty = s.clone();
                    let mut changed = false;
                    let mut parts = Vec::new();

                    for (name, field) in &fields.fields {
                        let Some(field_ty) = &field.ty else { continue };
                        let field_ident = format!("{js_ident}.{name}");
                        let Some((next_ty, runtime)) =
                            self.apply_inner(types, field_ty, &field_ident, stack)
                        else {
                            continue;
                        };

                        if let Some(next_ty) = next_ty
                            && let Fields::Named(fields) = &mut ty.fields
                            && let Some((_, field)) =
                                fields.fields.iter_mut().find(|(n, _)| n == name)
                        {
                            field.ty = Some(next_ty);
                            changed = true;
                        }
                        parts.push(format!("{name}:{runtime}"));
                    }

                    if parts.is_empty() {
                        None
                    } else {
                        Some((
                            changed.then_some(DataType::Struct(ty)),
                            spread_transform(js_ident, parts),
                        ))
                    }
                }
                Fields::Unnamed(fields) => {
                    let mut ty = s.clone();
                    let mut changed = false;
                    let parts = fields
                        .fields
                        .iter()
                        .enumerate()
                        .filter_map(|(idx, field)| {
                            let field_ty = field.ty.as_ref()?;
                            let field_ident = format!("{js_ident}[{idx}]");
                            let (next_ty, runtime) =
                                self.apply_inner(types, field_ty, &field_ident, stack)?;

                            if let Some(next_ty) = next_ty
                                && let Fields::Unnamed(fields) = &mut ty.fields
                            {
                                fields.fields[idx].ty = Some(next_ty);
                                changed = true;
                            }

                            Some(format!("{idx}:{runtime}"))
                        })
                        .collect::<Vec<_>>();

                    if parts.is_empty() {
                        None
                    } else {
                        Some((
                            changed.then_some(DataType::Struct(ty)),
                            spread_transform(js_ident, parts),
                        ))
                    }
                }
                Fields::Unit => None,
            },
            DataType::Tuple(tuple) => {
                let mut ty = tuple.clone();
                let mut changed = false;
                let parts = tuple
                    .elements
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, element)| {
                        let ident = format!("{js_ident}[{idx}]");
                        let (next_ty, runtime) = self.apply_inner(types, element, &ident, stack)?;
                        if let Some(next_ty) = next_ty {
                            ty.elements[idx] = next_ty;
                            changed = true;
                        }
                        Some(format!("{idx}:{runtime}"))
                    })
                    .collect::<Vec<_>>();

                if parts.is_empty() {
                    None
                } else {
                    Some((
                        changed.then_some(DataType::Tuple(ty)),
                        spread_transform(js_ident, parts),
                    ))
                }
            }
            DataType::List(list) => {
                let item = "i";
                let (next_ty, runtime) = self.apply_inner(types, &list.ty, item, stack)?;
                let mut ty = list.clone();
                let mut changed = false;
                if let Some(next_ty) = next_ty {
                    ty.ty = Box::new(next_ty);
                    changed = true;
                }
                Some((
                    changed.then_some(DataType::List(ty)),
                    format!("{js_ident}.map({item}=>{runtime})"),
                ))
            }
            DataType::Nullable(inner) => {
                let (next_ty, runtime) = self.apply_inner(types, inner, js_ident, stack)?;
                Some((
                    next_ty.map(|dt| DataType::Nullable(Box::new(dt))),
                    format!("{js_ident}==null?{js_ident}:{runtime}"),
                ))
            }
            DataType::Intersection(items) => {
                let mut ty = items.clone();
                let mut changed = false;
                let parts = items
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, item)| {
                        let (next_ty, runtime) = self.apply_inner(types, item, js_ident, stack)?;
                        if let Some(next_ty) = next_ty {
                            ty[idx] = next_ty;
                            changed = true;
                        }
                        Some(runtime)
                    })
                    .collect::<Vec<_>>();

                match parts.as_slice() {
                    [] => None,
                    [runtime] => Some((
                        changed.then_some(DataType::Intersection(ty)),
                        runtime.clone(),
                    )),
                    _ => Some((
                        changed.then_some(DataType::Intersection(ty)),
                        spread_transform(
                            "",
                            parts.into_iter().map(|p| format!("...{p}")).collect(),
                        ),
                    )),
                }
            }
            DataType::Map(_)
            | DataType::Enum(_)
            | DataType::Primitive(_)
            | DataType::Generic(_)
            | DataType::Reference(Reference::Opaque(_)) => None,
        };

        self.apply_remapper(dt, js_ident, result)
    }

    fn apply_remapper(
        &self,
        dt: &DataType,
        js_ident: &str,
        result: Option<(Option<DataType>, String)>,
    ) -> Option<(Option<DataType>, String)> {
        let Some(remapper) = self.remapper.as_ref() else {
            return result;
        };

        let remapped = remapper.remap_dt(
            result
                .as_ref()
                .and_then(|(dt, _)| dt.clone())
                .unwrap_or_else(|| dt.clone()),
        );

        if remapped == *dt {
            result
        } else if let Some((_, runtime)) = result {
            Some((Some(remapped), runtime))
        } else {
            Some((Some(remapped), js_ident.to_owned()))
        }
    }
}

fn spread_transform(js_ident: &str, mut parts: Vec<String>) -> String {
    if !js_ident.is_empty() {
        parts.insert(0, format!("...{js_ident}"));
    }
    format!("{{{}}}", parts.join(","))
}
