use specta::{Type, TypeCollection};
use specta_typescript::JSDoc;

#[derive(Type)]
struct Testing {
    a: String,
    b: i32,
}

fn main() {
    // let types = TypeCollection::default().register::<Testing>();
    // println!("{:#?}", specta_typescript::Typescript::new().export(&types));

    // let types = TypeCollection::default().register::<Testing>();

    // println!("{}", JSDoc::default().export(&types).unwrap());
}

// // This file has been generated by Specta. DO NOT EDIT.

// export type Testing = { a: string; b: number };

// // This file has been generated by Specta. DO NOT EDIT.

// export type Testing = { a: string; b: number };

// /**
//  * @typedef { string } Custom
//  */
