use specta::{Type, TypeCollection};
use specta_typescript::{Exporter, Typescript};

#[derive(Type)]
pub struct One {
    a: String,
    b: testing::Testing,
}

mod testing {
    use super::*;

    #[derive(Type)]
    pub struct Testing {
        c: char,
    }
}

#[derive(Type)]
pub struct MyChannel;

fn main() {
    let mut types = TypeCollection::default()
        .register::<One>()
        .register::<MyChannel>();

    // Demonstrate that specta::datatype::collect works
    let result = specta::datatype::collect(|| {
        One::definition(&mut types);
    });
    println!(
        "Collected types: {:?}",
        result.map(|ndt| ndt.name().clone()).collect::<Vec<_>>()
    );

    let _channel_ref = MyChannel::definition(&mut types);

    // Example 1: Basic export with framework_prelude
    println!("\n=== Example 1: framework_prelude ===");
    Exporter::from(Typescript::default())
        .framework_prelude(|ndts| {
            let mut result = String::from(
                "// This file has been generated by Specta. Do not edit this file manually.\n",
            );
            for ndt in ndts {
                // Check if this is the MyChannel type and add a custom import
                if ndt.name() == "MyChannel" {
                    result.push_str("import { Channel } from '@tauri-apps/api/channel';\n");
                }
            }
            result.into()
        })
        .layout(specta_typescript::Layout::Files)
        .export_to("./framework_test", &types)
        .unwrap();

    println!("Exported to ./framework_test with custom prelude");

    // Example 2: Export with framework_runtime that uses collect()
    println!("\n=== Example 2: framework_runtime with collect() ===");
    let types2 = TypeCollection::default().register::<One>();

    Exporter::from(Typescript::default())
        .framework_prelude(|_| "// Generated types with runtime\n".into())
        .framework_runtime(|| {
            // This demonstrates that types referenced in framework_runtime
            // will be collected and their imports will be generated
            "export const runtimeHelper = () => console.log('Helper function');\n".into()
        })
        .export(&types2)
        .map(|content| {
            println!("Generated content with runtime:\n{}", content);
        })
        .unwrap();
}
